/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ravi_jaiswal
 */
public class AddStudents extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public AddStudents() {
        initComponents();
          this.setResizable(false);
        addTitleIcon();
        injectCourseIntoList();

    }
    
    private void addTitleIcon(){
        ImageIcon icon = new ImageIcon("src/Images/college.png");
        this.setIconImage(icon.getImage());
    }
     private void injectCourseIntoList() {//fetchiching courses from table and add data into course combo......
        String query="SELECT * FROM course";
        fmsConnection con = new fmsConnection(query);
        
        try {
            ResultSet rs= con.pStmt.executeQuery();
            while(rs.next()){
               courseCombo2.addItem(rs.getString("courseName"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FeesAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fathersNameLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        countryLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ContactNoLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fNameTxt = new javax.swing.JTextField();
        lNameTxt = new javax.swing.JTextField();
        fatherNTxt = new javax.swing.JTextField();
        dobTxt = new com.toedter.calendar.JDateChooser();
        contTxt = new javax.swing.JTextField();
        repoLogoLbl7 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jSeparator1 = new javax.swing.JSeparator();
        mohersNameLbl1 = new javax.swing.JLabel();
        motherNTxt = new javax.swing.JTextField();
        courseLbl = new javax.swing.JLabel();
        courseCombo2 = new javax.swing.JComboBox<>();
        EmailLbl = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        fNameErrMsg = new javax.swing.JLabel();
        lNameErrMsg = new javax.swing.JLabel();
        FatherNameErrMsg = new javax.swing.JLabel();
        motherNameErrMsg = new javax.swing.JLabel();
        cntctErrMsg = new javax.swing.JLabel();
        EmailErrMsg = new javax.swing.JLabel();
        dobErrMsg = new javax.swing.JLabel();
        passErrMsg = new javax.swing.JLabel();
        countryErrMsg = new javax.swing.JLabel();
        countryTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        repoLogoLbl15 = new javax.swing.JLabel();
        repoLogoLbl6 = new javax.swing.JLabel();
        repoLogoLbl8 = new javax.swing.JLabel();
        repoLogoLbl1 = new javax.swing.JLabel();
        repoLogoLbl2 = new javax.swing.JLabel();
        repoLogoLbl10 = new javax.swing.JLabel();
        repoLogoLbl9 = new javax.swing.JLabel();
        repoLogoLbl11 = new javax.swing.JLabel();
        repoLogoLbl13 = new javax.swing.JLabel();
        repoLogoLbl16 = new javax.swing.JLabel();
        repoLogoLbl17 = new javax.swing.JLabel();
        repoLogoLbl18 = new javax.swing.JLabel();
        repoLogoLbl19 = new javax.swing.JLabel();
        repoLogoLbl20 = new javax.swing.JLabel();
        repoLogoLbl21 = new javax.swing.JLabel();
        repoLogoLbl22 = new javax.swing.JLabel();
        repoLogoLbl23 = new javax.swing.JLabel();
        repoLogoLbl24 = new javax.swing.JLabel();
        repoLogoLbl25 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signup");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(121, 25, 255));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(235, 0, 19));
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ux.png"))); // NOI18N
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 280, 280));

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset_btn.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 710, 120, -1));

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 197, 2));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 197, 2));
        kGradientPanel2.setOpaque(false);
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name :");
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name :");
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 105, 130, 30));

        fathersNameLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        fathersNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        fathersNameLbl.setText("Father's name:");
        kGradientPanel2.add(fathersNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 170, 30));

        addressLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        addressLbl.setForeground(new java.awt.Color(255, 255, 255));
        addressLbl.setText("Address");
        kGradientPanel2.add(addressLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 170, 30));

        countryLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        countryLbl.setForeground(new java.awt.Color(255, 255, 255));
        countryLbl.setText("country:");
        kGradientPanel2.add(countryLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 455, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("D.O.B :");
        kGradientPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 90, 30));

        ContactNoLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        ContactNoLbl.setForeground(new java.awt.Color(255, 255, 255));
        ContactNoLbl.setText("Contact No. :");
        kGradientPanel2.add(ContactNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 140, 30));

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signup.png"))); // NOI18N
        jButton1.setText("ADD");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 150, 40));

        fNameTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        fNameTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTxtActionPerformed(evt);
            }
        });
        fNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fNameTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fNameTxtKeyTyped(evt);
            }
        });
        kGradientPanel2.add(fNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 170, 30));

        lNameTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTxtActionPerformed(evt);
            }
        });
        lNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lNameTxtKeyReleased(evt);
            }
        });
        kGradientPanel2.add(lNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 105, 170, 30));

        fatherNTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        fatherNTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherNTxtActionPerformed(evt);
            }
        });
        fatherNTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fatherNTxtKeyReleased(evt);
            }
        });
        kGradientPanel2.add(fatherNTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 170, 30));

        dobTxt.setPreferredSize(new java.awt.Dimension(88, 20));
        dobTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dobTxtKeyReleased(evt);
            }
        });
        kGradientPanel2.add(dobTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 170, 30));

        contTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        contTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contTxtActionPerformed(evt);
            }
        });
        contTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contTxtKeyReleased(evt);
            }
        });
        kGradientPanel2.add(contTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 170, 30));

        repoLogoLbl7.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl7.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/analysis (1).png"))); // NOI18N
        kGradientPanel2.add(repoLogoLbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -260, 250, 300));

        kGradientPanel3.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel3.setkStartColor(new java.awt.Color(255, 255, 255));

        kGradientPanel4.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel4.setkStartColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        kGradientPanel2.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 96, 135, -1));
        kGradientPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        mohersNameLbl1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        mohersNameLbl1.setForeground(new java.awt.Color(255, 255, 255));
        mohersNameLbl1.setText("Mother's name:");
        kGradientPanel2.add(mohersNameLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 195, 170, 30));

        motherNTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        motherNTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                motherNTxtKeyReleased(evt);
            }
        });
        kGradientPanel2.add(motherNTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 195, 170, 30));

        courseLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        courseLbl.setForeground(new java.awt.Color(255, 255, 255));
        courseLbl.setText("Course:");
        kGradientPanel2.add(courseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 170, 30));

        courseCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseCombo2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(courseCombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 170, 25));

        EmailLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        EmailLbl.setForeground(new java.awt.Color(255, 255, 255));
        EmailLbl.setText("Email:");
        kGradientPanel2.add(EmailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 140, 20));

        emailTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        emailTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTxtKeyReleased(evt);
            }
        });
        kGradientPanel2.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 365, 170, 30));

        fNameErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fNameErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(fNameErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 250, 20));

        lNameErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lNameErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(lNameErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 250, 20));

        FatherNameErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FatherNameErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(FatherNameErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 250, 20));

        motherNameErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        motherNameErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(motherNameErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 250, 20));

        cntctErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cntctErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(cntctErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 210, 20));

        EmailErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EmailErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(EmailErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 250, 20));

        dobErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dobErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(dobErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 240, 20));

        passErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(passErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 240, 20));

        countryErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        countryErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(countryErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 240, 20));

        countryTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        countryTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        countryTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryTxtActionPerformed(evt);
            }
        });
        countryTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                countryTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                countryTxtKeyTyped(evt);
            }
        });
        kGradientPanel2.add(countryTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 170, 30));

        addressTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        addressTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        addressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtActionPerformed(evt);
            }
        });
        addressTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressTxtKeyTyped(evt);
            }
        });
        kGradientPanel2.add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 170, 30));

        repoLogoLbl15.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl15.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/analysis (1).png"))); // NOI18N
        kGradientPanel2.add(repoLogoLbl15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 303, -1, -1));

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 420, 560));

        repoLogoLbl6.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl6.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 250, 260));

        repoLogoLbl8.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl8.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 290, -1, -1));

        repoLogoLbl1.setFont(new java.awt.Font("Jokerman", 0, 30)); // NOI18N
        repoLogoLbl1.setForeground(new java.awt.Color(51, 199, 202));
        repoLogoLbl1.setText("Feature s of F.M.S...");
        kGradientPanel1.add(repoLogoLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 290, 40));

        repoLogoLbl2.setFont(new java.awt.Font("Jokerman", 0, 30)); // NOI18N
        repoLogoLbl2.setForeground(new java.awt.Color(255, 255, 51));
        repoLogoLbl2.setText("SignUp To get Access...");
        kGradientPanel1.add(repoLogoLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 340, 40));

        repoLogoLbl10.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl10.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 40, -1, -1));

        repoLogoLbl9.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl9.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, -140, -1, -1));

        repoLogoLbl11.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl11.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, -140, -1, -1));

        repoLogoLbl13.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl13.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -140, -1, -1));

        repoLogoLbl16.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl16.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 150, 120));

        repoLogoLbl17.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl17.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 100, 70));

        repoLogoLbl18.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl18.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 630, 70, 60));

        repoLogoLbl19.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl19.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 340, 100, 60));

        repoLogoLbl20.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl20.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 250, 80, 60));

        repoLogoLbl21.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl21.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 110, 150, 120));

        repoLogoLbl22.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl22.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 150, 120));

        repoLogoLbl23.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl23.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 100, 60));

        repoLogoLbl24.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl24.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 630, 70, 60));

        repoLogoLbl25.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl25.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl25, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 540, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Jokerman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AddStudents");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 230, 40));
        kGradientPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 36, 200, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameTxtActionPerformed

    private void fatherNTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherNTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherNTxtActionPerformed

    private void lNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(myValidate()){//Submit button actions .............
        insertDataIntoDb(); 
        reset();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    //My methods..............................................
    
    String fName,lName,fatherName,motherName,cntct,email,address,country;
    Date dob1;
    int course;
    private boolean flag[]=new boolean[10];
   
    public boolean myValidate(){
         flag[0]=true;
         flag[5]=true;
         fName=fNameTxt.getText();
         lName=lNameTxt.getText();
         fatherName=fatherNTxt.getText();
         motherName=motherNTxt.getText();
         dob1=dobTxt.getDate();
         cntct=contTxt.getText();
         email= emailTxt.getText();
         address= addressTxt.getText();
         country= countryTxt.getText();
         course=courseCombo2.getSelectedIndex();
        
         return checkEmptyField()&&flagResult(); 
    }
    private boolean flagResult(){
        boolean res=true;
        int i=0;
        for (boolean b : flag) {
           res=res&&b; 
           
            System.out.println("*****************flag["+i+"]="+b);
            i++;
        }
        return res;
    }
    public boolean checkEmptyField(){//check for empty fields..........
        if(fName.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Firstname!");
        return false;
        }
        if(lName.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Lastname!");
        return false;
        }
        if(fatherName.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter fathername!");
        return false;
        }
        if(motherName.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Mothername!");
        return false;
        }
        if(dob1==null){
            JOptionPane.showMessageDialog(this, "please Select your DOB!");
            System.out.println("date..................."+dob1);
        return false;
        }
        if(cntct.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter your Contact!");
        return false;
        }
        if(email.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter email");
        return false;
        }
        if(address.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter address!");
        return false;
        }
        if(country.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter country name!");
        return false;
        }
     return true;
    }
    
    public boolean passMatch(String pass1, String pass2){
         if(!pass1.equals(pass2)){ 
             JOptionPane.showMessageDialog(this, "password and confirmPassword doesn't matched");
             return false;}
         return true;
    }
    
    public void reset(){
        fNameTxt.setText("");
        lNameTxt.setText("");
        fatherNTxt.setText("");
        motherNTxt.setText("");
        addressTxt.setText("");
        countryTxt.setText("");
        dobTxt.setDate(null);
        contTxt.setText("");
        emailTxt.setText("");
    }
    
    public boolean patternMatcher(String regex,String name){
    Pattern p = Pattern.compile(regex); 
    Matcher m= p.matcher(name);
    return m.find();
    }
    
    private void insertDataIntoDb(){
        //to convert default date format into yyyy-MM-dd format
         //note month must be MM not mm
        SimpleDateFormat dateFormat1= new SimpleDateFormat("yyyy-MM-dd");
        String dob2=dateFormat1.format(dobTxt.getDate());
        
        String query ="insert into student(first_name,last_name,father_name,mother_name,DOB,courseID,contact_no,email,address,country)values(?,?,?,?,?,?,?,?,?,?)";
        fmsConnection fc = new fmsConnection(query);
          
            
        try{
            fc.pStmt.setString(1,fNameTxt.getText());
            fc.pStmt.setString(2,lNameTxt.getText());
            fc.pStmt.setString(3,fatherNTxt.getText());
            fc.pStmt.setString(4,motherNTxt.getText());
            fc.pStmt.setString(5,dob2);
            fc.pStmt.setInt(6, courseCombo2.getSelectedIndex()+1);
            fc.pStmt.setString(7,contTxt.getText());
            fc.pStmt.setString(8,emailTxt.getText());
            fc.pStmt.setString(9,addressTxt.getText());
            fc.pStmt.setString(10, countryTxt.getText());
            fc.pStmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Student Added...");
            fc.con.close();
        }
        catch(Exception e){
            System.out.println("Student Addition failed");
            e.printStackTrace();
        }
    }
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fNameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameTxtKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fNameTxtKeyTyped

    private void fNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameTxtKeyReleased
//         TODO add your handling code here:
        if(patternMatcher("^[a-zA-Z]+$",fNameTxt.getText())){
            fNameErrMsg.setText("");
            flag[1]=true;
        }
        else{
            fNameErrMsg.setText("*FName must contain only Alphabets[a-zA-Z]");
            flag[1]=false;
        }
    }//GEN-LAST:event_fNameTxtKeyReleased

    private void lNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNameTxtKeyReleased
        // TODO add your handling code here:
        if(patternMatcher("^[a-zA-Z]+$",lNameTxt.getText())){
            lNameErrMsg.setText("");
             flag[2]=true;
        }
        else{
            lNameErrMsg.setText("*LName must contain only Alphabets[a-zA-Z]");
            flag[2]=false;
        }
    }//GEN-LAST:event_lNameTxtKeyReleased

    private void fatherNTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherNTxtKeyReleased
        // TODO add your handling code here:
//        if(patternMatcher("^[a-zA-Z\s]+$",fatherNTxt.getText())){
          if(patternMatcher("^[a-zA-Z\\s]+$", fatherNTxt.getText())){           
          FatherNameErrMsg.setText("");
             flag[3]=true;
        }
        else{
            FatherNameErrMsg.setText("Alphabets only");
             flag[3]=false;
        }
    }//GEN-LAST:event_fatherNTxtKeyReleased

    private void contTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contTxtKeyReleased
        // TODO add your handling code here:
        if(patternMatcher("^[1-9][0-9]{9}$",contTxt.getText())){
            cntctErrMsg.setText("");
             flag[6]=true;
        }
        else{
            cntctErrMsg.setText("*Invalid number");
             flag[6]=false;
        }
    }//GEN-LAST:event_contTxtKeyReleased

    private void contTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contTxtActionPerformed

    private void motherNTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motherNTxtKeyReleased
//        if(patternMatcher("^[a-zA-Z\s]+$",motherNTxt.getText())){
            if(patternMatcher("^[a-zA-Z\\s]+$", motherNTxt.getText())){
            motherNameErrMsg.setText("");
             flag[4]=true;
        }
        else{
            motherNameErrMsg.setText("Alphabets only");
             flag[4]=false;
        }
    }//GEN-LAST:event_motherNTxtKeyReleased

    private void courseCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseCombo2ActionPerformed
//        String course;
//        course =courseCombo.getSelectedItem().toString();
//        courseTxt.setText(course);
    }//GEN-LAST:event_courseCombo2ActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void emailTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTxtKeyReleased
       if(patternMatcher("[A-Za-z0-9][A-Za-z0-9_.]*@[A-Za-z0-9]+([.][A-Za-z]+)+",emailTxt.getText())){
            EmailErrMsg.setText("");
             flag[7]=true;
        }
        else{
            EmailErrMsg.setText("invalid mailID");
             flag[7]=false;
        }
    }//GEN-LAST:event_emailTxtKeyReleased

    private void dobTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobTxtKeyReleased
         
    }//GEN-LAST:event_dobTxtKeyReleased

    private void countryTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTxtActionPerformed

    private void countryTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countryTxtKeyReleased
        // TODO add your handling code here:
//        if(patternMatcher("^[a-zA-Z\s]+$",countryTxt.getText())){
            if(patternMatcher("^[a-zA-Z\\s]+$", countryTxt.getText())){
            countryErrMsg.setText("");
             flag[9]=true;
        }
        else{
            countryErrMsg.setText("Alphabets only");
             flag[9]=false;
        }
    }//GEN-LAST:event_countryTxtKeyReleased

    private void countryTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countryTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTxtKeyTyped

    private void addressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtActionPerformed

    private void addressTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTxtKeyReleased
         flag[8]=true;
    }//GEN-LAST:event_addressTxtKeyReleased

    private void addressTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtKeyTyped

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.dispose();
        AdminDashboard home = new AdminDashboard();
        home.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {//..........main function here..........
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContactNoLbl;
    private javax.swing.JLabel EmailErrMsg;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JLabel FatherNameErrMsg;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JLabel cntctErrMsg;
    private javax.swing.JTextField contTxt;
    private javax.swing.JLabel countryErrMsg;
    private javax.swing.JLabel countryLbl;
    private javax.swing.JTextField countryTxt;
    private javax.swing.JComboBox<String> courseCombo2;
    private javax.swing.JLabel courseLbl;
    private javax.swing.JLabel dobErrMsg;
    private com.toedter.calendar.JDateChooser dobTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel fNameErrMsg;
    private javax.swing.JTextField fNameTxt;
    private javax.swing.JTextField fatherNTxt;
    private javax.swing.JLabel fathersNameLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private javax.swing.JLabel lNameErrMsg;
    private javax.swing.JTextField lNameTxt;
    private javax.swing.JLabel mohersNameLbl1;
    private javax.swing.JTextField motherNTxt;
    private javax.swing.JLabel motherNameErrMsg;
    private javax.swing.JLabel passErrMsg;
    private javax.swing.JLabel repoLogoLbl1;
    private javax.swing.JLabel repoLogoLbl10;
    private javax.swing.JLabel repoLogoLbl11;
    private javax.swing.JLabel repoLogoLbl13;
    private javax.swing.JLabel repoLogoLbl15;
    private javax.swing.JLabel repoLogoLbl16;
    private javax.swing.JLabel repoLogoLbl17;
    private javax.swing.JLabel repoLogoLbl18;
    private javax.swing.JLabel repoLogoLbl19;
    private javax.swing.JLabel repoLogoLbl2;
    private javax.swing.JLabel repoLogoLbl20;
    private javax.swing.JLabel repoLogoLbl21;
    private javax.swing.JLabel repoLogoLbl22;
    private javax.swing.JLabel repoLogoLbl23;
    private javax.swing.JLabel repoLogoLbl24;
    private javax.swing.JLabel repoLogoLbl25;
    private javax.swing.JLabel repoLogoLbl6;
    private javax.swing.JLabel repoLogoLbl7;
    private javax.swing.JLabel repoLogoLbl8;
    private javax.swing.JLabel repoLogoLbl9;
    // End of variables declaration//GEN-END:variables
}
