/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ravi_jaiswal
 */
public class AdminViewCourse extends javax.swing.JFrame {

    /**
     * Creates new form AdminViewCourse
     */
    String currentTheme;
    public AdminViewCourse() {
          this.setResizable(false);
        initComponents();
        addTitleIcon();
        searchCourse();
         //theme settings..................................................begin 1
        currentTheme=Theme.getTheme();
        setCurrentTheme(currentTheme);
        //theme settings..................................................end
    }
    private void addTitleIcon(){
        ImageIcon icon = new ImageIcon("src/Images/college.png");
        this.setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPnl1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        themeToggleButton = new javax.swing.JToggleButton();
        homeBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        EditBtn = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        CourseBtn = new javax.swing.JPanel();
        crselbl = new javax.swing.JLabel();
        viewAllRecBtn = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        backBtn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        mainPnl2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCourse = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ViewCourse.........");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPnl1.setBackground(new java.awt.Color(242, 135, 5));
        MainPnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        MainPnl1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 130, 10));

        jLabel1.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/view all record.png"))); // NOI18N
        MainPnl1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 70));

        jLabel3.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ViewCourses,,");
        MainPnl1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        themeToggleButton.setBackground(new java.awt.Color(255, 255, 255));
        themeToggleButton.setText("Light");
        themeToggleButton.setFocusable(false);
        themeToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                themeToggleButtonItemStateChanged(evt);
            }
        });
        themeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeToggleButtonActionPerformed(evt);
            }
        });
        MainPnl1.add(themeToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 60, -1));

        homeBtn.setBackground(new java.awt.Color(242, 203, 5));
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_btn.png"))); // NOI18N
        jLabel12.setText("Home");
        homeBtn.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        MainPnl1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 205, 50));

        searchBtn.setBackground(new java.awt.Color(242, 203, 5));
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBtnMouseExited(evt);
            }
        });
        searchBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_btn.png"))); // NOI18N
        jLabel13.setText("S Record");
        searchBtn.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        MainPnl1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 205, 50));

        EditBtn.setBackground(new java.awt.Color(242, 203, 5));
        EditBtn.setForeground(new java.awt.Color(255, 255, 255));
        EditBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditBtnMouseExited(evt);
            }
        });
        EditBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit_btn.png"))); // NOI18N
        jLabel14.setText("Edit Course");
        EditBtn.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        MainPnl1.add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 205, 50));

        CourseBtn.setBackground(new java.awt.Color(242, 203, 5));
        CourseBtn.setForeground(new java.awt.Color(255, 255, 255));
        CourseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CourseBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CourseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CourseBtnMouseExited(evt);
            }
        });
        CourseBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crselbl.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        crselbl.setForeground(new java.awt.Color(255, 255, 255));
        crselbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/course_btn.png"))); // NOI18N
        crselbl.setText("Courses");
        CourseBtn.add(crselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        MainPnl1.add(CourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 205, 50));

        viewAllRecBtn.setBackground(new java.awt.Color(242, 203, 5));
        viewAllRecBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewAllRecBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewAllRecBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllRecBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewAllRecBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewAllRecBtnMouseExited(evt);
            }
        });
        viewAllRecBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/records_btn.png"))); // NOI18N
        jLabel16.setText("Records");
        viewAllRecBtn.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        MainPnl1.add(viewAllRecBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 205, 50));

        backBtn.setBackground(new java.awt.Color(242, 203, 5));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn.png"))); // NOI18N
        jLabel17.setText("Back");
        backBtn.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        MainPnl1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 205, 50));

        logoutBtn.setBackground(new java.awt.Color(242, 203, 5));
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        logoutBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout_btn.png"))); // NOI18N
        jLabel11.setText("Logout");
        logoutBtn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        MainPnl1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 205, 50));

        getContentPane().add(MainPnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 665));

        mainPnl2.setBackground(new java.awt.Color(242, 159, 100));
        mainPnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableCourse.setBackground(new java.awt.Color(0, 153, 204));
        tableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CourseID", "Course", "CourseFees", "CourseDuration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableCourse);

        mainPnl2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 490, 280));

        jLabel2.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Courses.....");
        mainPnl2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 200, 30));

        getContentPane().add(mainPnl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 870, 665));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
      DefaultTableModel model;
     private void searchCourse(){
     String query = "SELECT * FROM course";
     fmsConnection fc = new fmsConnection(query);
     try{
      ResultSet rs = fc.pStmt.executeQuery();
      while(rs.next()){
          String id = rs.getString("courseId");
          String name = rs.getString("courseName");
          String fees = rs.getString("courseFees");
          String duration = rs.getString("courseDuration");
//        String recieptNo = rs.getString("");
          Object obj[] = {id, name, fees, duration};
          model=(DefaultTableModel)tableCourse.getModel();
          model.addRow(obj);
     }
    }
    catch(Exception e){
        e.printStackTrace();
    }
    }
    
    
     private void darkTheme(){
    
     MainPnl1.setBackground(new Color(128,128,128));
     mainPnl2.setBackground(new Color(64,64,64));
     
     homeBtn.setBackground(new Color(64,64,64)); 
     searchBtn.setBackground(new Color(64,64,64)); 
     EditBtn.setBackground(new Color(64,64,64)); 
     CourseBtn.setBackground(new Color(64,64,64));
     viewAllRecBtn.setBackground(new Color(64,64,64));
     backBtn.setBackground(new Color(64,64,64)); 
     logoutBtn.setBackground(new Color(64,64,64)); 
    
    }
    private void lightTheme(){
    
     MainPnl1.setBackground(new Color(242,135,5));
     mainPnl2.setBackground(new Color(242,159,100));
    
      homeBtn.setBackground(new Color(242,203,5)); 
    searchBtn.setBackground(new Color(242,203,5)); 
      EditBtn.setBackground(new Color(242,203,5)); 
    CourseBtn.setBackground(new Color(242,203,5));
viewAllRecBtn.setBackground(new Color(242,203,5));
      backBtn.setBackground(new Color(242,203,5)); 
    logoutBtn.setBackground(new Color(242,203,5)); 
    
    }
    
     //theme setCurrentTheme........................................................begin 2
    private void setCurrentTheme(String currentTheme){
        if(currentTheme.equalsIgnoreCase("dark")){
            selectDark();//here(in DB) true means dark theme
        }
        else{
            selectLight();//here(in DB) true means light theme
        }
    }
    //theme setCurrentTheme........................................................end
    
    // theme select.................................................................begin 3
    private void selectDark(){
        System.out.println("SelectDark");
        themeToggleButton.setText("Dark");
        themeToggleButton.setBackground(new Color(0, 0, 0));
        themeToggleButton.setForeground(new Color(255, 255, 255));
        darkTheme();
   
    }
    private void selectLight(){
         System.out.println("selectLight");
        themeToggleButton.setText("Light");
        themeToggleButton.setBackground(new Color(255, 255, 255));
        themeToggleButton.setForeground(new Color(0, 0, 0));
        lightTheme();
      
    }
    // theme select.................................................................end  3
    
    private void themeToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_themeToggleButtonItemStateChanged
        int state = evt.getStateChange();

        // if selectDark print dark theme in console
        if (state == java.awt.event.ItemEvent.SELECTED) {
            selectDark();
            Theme.setTheme("dark");
        }
        else { // else  print light theme theme in console
            selectLight();
            Theme.setTheme("light");
        }
    }//GEN-LAST:event_themeToggleButtonItemStateChanged

    private void themeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeToggleButtonActionPerformed

    }//GEN-LAST:event_themeToggleButtonActionPerformed

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.dispose();
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            homeBtn.setBackground(new Color(96, 96, 96));
        } else {
            homeBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            homeBtn.setBackground(new Color(64, 64, 64));
        } else {
            homeBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_homeBtnMouseExited

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        this.dispose();
        SearchRecord ad = new SearchRecord();
        ad.setVisible(true);
    }//GEN-LAST:event_searchBtnMouseClicked

    private void searchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            searchBtn.setBackground(new Color(96, 96, 96));
        } else {
            searchBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_searchBtnMouseEntered

    private void searchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            searchBtn.setBackground(new Color(64, 64, 64));
        } else {
            searchBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_searchBtnMouseExited

    private void EditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseClicked
        this.dispose();
        EditCourse ad = new EditCourse();
        ad.setVisible(true);
    }//GEN-LAST:event_EditBtnMouseClicked

    private void EditBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            EditBtn.setBackground(new Color(96, 96, 96));
        } else {
            EditBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_EditBtnMouseEntered

    private void EditBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            EditBtn.setBackground(new Color(64, 64, 64));
        } else {
            EditBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_EditBtnMouseExited

    private void CourseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseClicked
        this.dispose();
        AdminViewCourse ad = new AdminViewCourse();
        ad.setVisible(true);
    }//GEN-LAST:event_CourseBtnMouseClicked

    private void CourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            CourseBtn.setBackground(new Color(96, 96, 96));
        } else {
            CourseBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_CourseBtnMouseEntered

    private void CourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            CourseBtn.setBackground(new Color(64, 64, 64));
        } else {
            CourseBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_CourseBtnMouseExited

    private void viewAllRecBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllRecBtnMouseClicked
        this.dispose();
        ViewAllRecords ad = new ViewAllRecords();
        ad.setVisible(true);
    }//GEN-LAST:event_viewAllRecBtnMouseClicked

    private void viewAllRecBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllRecBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            viewAllRecBtn.setBackground(new Color(96, 96, 96));
        } else {
            viewAllRecBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_viewAllRecBtnMouseEntered

    private void viewAllRecBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllRecBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            viewAllRecBtn.setBackground(new Color(64, 64, 64));
        } else {
            viewAllRecBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_viewAllRecBtnMouseExited

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        this.dispose();
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
    }//GEN-LAST:event_backBtnMouseClicked

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            backBtn.setBackground(new Color(96, 96, 96));
        } else {
            backBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            backBtn.setBackground(new Color(64, 64, 64));
        } else {
            backBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_backBtnMouseExited

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        this.dispose();
        HomeMain ad = new HomeMain();
        ad.setVisible(true);
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            logoutBtn.setBackground(new Color(96, 96, 96));
        } else {
            logoutBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            logoutBtn.setBackground(new Color(64, 64, 64));
        } else {
            logoutBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_logoutBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CourseBtn;
    private javax.swing.JPanel EditBtn;
    private javax.swing.JPanel MainPnl1;
    private javax.swing.JPanel backBtn;
    private javax.swing.JLabel crselbl;
    private javax.swing.JPanel homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JPanel mainPnl2;
    private javax.swing.JPanel searchBtn;
    private javax.swing.JTable tableCourse;
    private javax.swing.JToggleButton themeToggleButton;
    private javax.swing.JPanel viewAllRecBtn;
    // End of variables declaration//GEN-END:variables
}
