/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ravi_jaiswal
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public AdminLogin() {
        initComponents();
          this.setResizable(false);
         System.out.println("Welcome to login page....");
        addTitleIcon();
    }
    private void addTitleIcon(){
        ImageIcon icon = new ImageIcon("src/Images/college.png");
        this.setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        uNameTxt = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        pwdTxt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        repoLogoLbl19 = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();
        repoLogoLbl6 = new javax.swing.JLabel();
        repoLogoLbl20 = new javax.swing.JLabel();
        repoLogoLbl21 = new javax.swing.JLabel();
        repoLogoLbl16 = new javax.swing.JLabel();
        repoLogoLbl24 = new javax.swing.JLabel();
        repoLogoLbl18 = new javax.swing.JLabel();
        repoLogoLbl23 = new javax.swing.JLabel();
        repoLogoLbl17 = new javax.swing.JLabel();
        repoLogoLbl22 = new javax.swing.JLabel();
        repoLogoLbl2 = new javax.swing.JLabel();
        repoLogoLbl1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        repoLogoLbl5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        repoLogoLbl26 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        repoLogoLbl11 = new javax.swing.JLabel();
        repoLogoLbl9 = new javax.swing.JLabel();
        repoLogoLbl13 = new javax.swing.JLabel();
        repoLogoLbl10 = new javax.swing.JLabel();
        repoLogoLbl8 = new javax.swing.JLabel();
        repoLogoLbl25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN FORM");
        setMinimumSize(new java.awt.Dimension(910, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(121, 25, 255));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(235, 0, 19));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(0, 0));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 51));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Username");
        kGradientPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 153, 40));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Password");
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, 40));

        kGradientPanel3.setBackground(new java.awt.Color(255, 255, 51));
        kGradientPanel3.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel3.setkStartColor(new java.awt.Color(65, 201, 162));

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        kGradientPanel2.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 210, 1));

        kGradientPanel4.setBackground(new java.awt.Color(255, 255, 51));
        kGradientPanel4.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel4.setkStartColor(new java.awt.Color(65, 201, 162));

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        kGradientPanel2.add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, 1));

        uNameTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        uNameTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        kGradientPanel2.add(uNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 300, 40));

        loginBtn.setBackground(new java.awt.Color(51, 204, 0));
        loginBtn.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 170, 40));

        pwdTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pwdTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        kGradientPanel2.add(pwdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 300, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/design-thinking.png"))); // NOI18N
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 190, 277, 280));

        repoLogoLbl19.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl19.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        kGradientPanel2.add(repoLogoLbl19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 70, 60));

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 370, 450));

        resetBtn.setBackground(new java.awt.Color(255, 51, 0));
        resetBtn.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset_btn.png"))); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        kGradientPanel1.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 680, 120, -1));

        repoLogoLbl6.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl6.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 250, 260));

        repoLogoLbl20.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl20.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 250, 80, 60));

        repoLogoLbl21.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl21.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 110, 150, 120));

        repoLogoLbl16.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl16.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 150, 120));

        repoLogoLbl24.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl24.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl24, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 630, 70, 60));

        repoLogoLbl18.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl18.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 640, 70, 60));

        repoLogoLbl23.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl23.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 100, 60));

        repoLogoLbl17.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl17.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 100, 70));

        repoLogoLbl22.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl22.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 150, 120));

        repoLogoLbl2.setFont(new java.awt.Font("Jokerman", 0, 30)); // NOI18N
        repoLogoLbl2.setForeground(new java.awt.Color(255, 255, 51));
        repoLogoLbl2.setText("THINK INNOVATIVE");
        kGradientPanel1.add(repoLogoLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 340, 40));

        repoLogoLbl1.setFont(new java.awt.Font("Jokerman", 0, 30)); // NOI18N
        repoLogoLbl1.setForeground(new java.awt.Color(51, 199, 202));
        repoLogoLbl1.setText("BOOST YOUR CAREER");
        kGradientPanel1.add(repoLogoLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 290, 40));

        jLabel7.setFont(new java.awt.Font("Jokerman", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Login");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 160, 60));

        repoLogoLbl5.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl5.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 510, 510));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/design-thinking.png"))); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 277, 280));

        repoLogoLbl26.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl26.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 340, 100, 60));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADMIN");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 80, 10));

        repoLogoLbl11.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl11.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, -140, -1, -1));

        repoLogoLbl9.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl9.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, -140, -1, -1));

        repoLogoLbl13.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl13.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -140, -1, -1));

        repoLogoLbl10.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl10.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 40, -1, -1));

        repoLogoLbl8.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl8.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 290, -1, -1));

        repoLogoLbl25.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl25.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl25, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 540, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    my handling methods............
    
    
    private boolean myValidate(){
    return checkEmptyFields();
    }
    
    private boolean checkEmptyFields(){
        if(uNameTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Username can't be empty..");
            return false;
        }
        if(pwdTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Password can't be empty..");
            return false;
        }
    return true;
    }
    
    private void reset(){
        uNameTxt.setText("");
        pwdTxt.setText("");
    }
    
    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:

        
        System.out.println("Login button clicked.");
        
        if(myValidate()){
           
            String uname=uNameTxt.getText();
            String pwd = pwdTxt.getText();
//             
            String query ="SELECT * FROM admin WHERE user_name=? and password=?"; 
            fmsConnection fc = new fmsConnection(query);
            try {
                fc.pStmt.setString(1, uname);
                fc.pStmt.setString(2, pwd);
                ResultSet rs= fc.pStmt.executeQuery();
                if(rs.next()){
                    System.out.println("test.");
                    JOptionPane.showMessageDialog(this, "Login SuccessFull..");
                    AdminDashboard home = new AdminDashboard();
                    home.setVisible(true);
                    this.dispose();
                }
                else{
                JOptionPane.showMessageDialog(this, "Please Enter Correct Username and Password..");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.dispose();
         HomeMain home = new HomeMain();
        home.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField pwdTxt;
    private javax.swing.JLabel repoLogoLbl1;
    private javax.swing.JLabel repoLogoLbl10;
    private javax.swing.JLabel repoLogoLbl11;
    private javax.swing.JLabel repoLogoLbl13;
    private javax.swing.JLabel repoLogoLbl16;
    private javax.swing.JLabel repoLogoLbl17;
    private javax.swing.JLabel repoLogoLbl18;
    private javax.swing.JLabel repoLogoLbl19;
    private javax.swing.JLabel repoLogoLbl2;
    private javax.swing.JLabel repoLogoLbl20;
    private javax.swing.JLabel repoLogoLbl21;
    private javax.swing.JLabel repoLogoLbl22;
    private javax.swing.JLabel repoLogoLbl23;
    private javax.swing.JLabel repoLogoLbl24;
    private javax.swing.JLabel repoLogoLbl25;
    private javax.swing.JLabel repoLogoLbl26;
    private javax.swing.JLabel repoLogoLbl5;
    private javax.swing.JLabel repoLogoLbl6;
    private javax.swing.JLabel repoLogoLbl8;
    private javax.swing.JLabel repoLogoLbl9;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField uNameTxt;
    // End of variables declaration//GEN-END:variables
}
