/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Ravi_jaiswal
 */
public class EditCourse extends javax.swing.JFrame {
    String currentTheme;
    /**
     * Creates new form EditCourse
     */
    public EditCourse() {
          this.setResizable(false);
        addTitleIcon();
        initComponents();
        searchCourse();
//        courseIdTxt.setEditable(false);

 //theme settings..................................................begin 1
        currentTheme=Theme.getTheme();
        setCurrentTheme(currentTheme);
        //theme settings..................................................end
    }
    private void addTitleIcon(){
        ImageIcon icon = new ImageIcon("src/Images/college.png");
        this.setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCourse = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        courseIdTxt = new javax.swing.JTextField();
        courseNameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FeesTxt = new javax.swing.JTextField();
        durationTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        mainPnl1 = new javax.swing.JPanel();
        themeToggleButton = new javax.swing.JToggleButton();
        homeBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        EditBtn = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        CourseBtn = new javax.swing.JPanel();
        crselbl = new javax.swing.JLabel();
        viewAllRecBtn = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        backBtn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EditCourse");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPnl2.setBackground(new java.awt.Color(242, 159, 100));
        mainPnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course_ID", "Course", "Fees", "Duration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCourseMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableCourseMouseReleased(evt);
            }
        });
        tableCourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableCourseKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableCourse);
        if (tableCourse.getColumnModel().getColumnCount() > 0) {
            tableCourse.getColumnModel().getColumn(0).setResizable(false);
            tableCourse.getColumnModel().getColumn(1).setResizable(false);
            tableCourse.getColumnModel().getColumn(2).setResizable(false);
            tableCourse.getColumnModel().getColumn(3).setResizable(false);
        }

        mainPnl2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 550, 520));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Course ID :");
        mainPnl2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 310, 130, 30));

        courseIdTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        courseIdTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        courseIdTxt.setAutoscrolls(false);
        courseIdTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        courseIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseIdTxtActionPerformed(evt);
            }
        });
        courseIdTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                courseIdTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                courseIdTxtKeyTyped(evt);
            }
        });
        mainPnl2.add(courseIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 170, 30));

        courseNameTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        courseNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseNameTxtActionPerformed(evt);
            }
        });
        courseNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                courseNameTxtKeyReleased(evt);
            }
        });
        mainPnl2.add(courseNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Name :");
        mainPnl2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 350, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Fees :");
        mainPnl2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 390, 120, 30));

        FeesTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        FeesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeesTxtActionPerformed(evt);
            }
        });
        FeesTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FeesTxtKeyReleased(evt);
            }
        });
        mainPnl2.add(FeesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 170, 30));

        durationTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        durationTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        durationTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationTxtActionPerformed(evt);
            }
        });
        durationTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                durationTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                durationTxtKeyTyped(evt);
            }
        });
        mainPnl2.add(durationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 170, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Duration :");
        mainPnl2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 430, 130, 30));

        deleteBtn.setBackground(new java.awt.Color(255, 51, 0));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        mainPnl2.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 80, 30));

        updateBtn.setBackground(new java.awt.Color(255, 102, 0));
        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        mainPnl2.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 80, 30));

        addBtn.setBackground(new java.awt.Color(0, 204, 51));
        addBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        mainPnl2.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, 80, 30));

        getContentPane().add(mainPnl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 665));

        mainPnl1.setBackground(new java.awt.Color(242, 135, 5));
        mainPnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        themeToggleButton.setBackground(new java.awt.Color(255, 255, 255));
        themeToggleButton.setText("Light");
        themeToggleButton.setFocusable(false);
        themeToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                themeToggleButtonItemStateChanged(evt);
            }
        });
        themeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeToggleButtonActionPerformed(evt);
            }
        });
        mainPnl1.add(themeToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 60, -1));

        homeBtn.setBackground(new java.awt.Color(242, 203, 5));
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_btn.png"))); // NOI18N
        jLabel12.setText("Home");
        homeBtn.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        mainPnl1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 205, 50));

        searchBtn.setBackground(new java.awt.Color(242, 203, 5));
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBtnMouseExited(evt);
            }
        });
        searchBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_btn.png"))); // NOI18N
        jLabel13.setText("S Record");
        searchBtn.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        mainPnl1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 205, 50));

        EditBtn.setBackground(new java.awt.Color(242, 203, 5));
        EditBtn.setForeground(new java.awt.Color(255, 255, 255));
        EditBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditBtnMouseExited(evt);
            }
        });
        EditBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit_btn.png"))); // NOI18N
        jLabel14.setText("Edit Course");
        EditBtn.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        mainPnl1.add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 205, 50));

        CourseBtn.setBackground(new java.awt.Color(242, 203, 5));
        CourseBtn.setForeground(new java.awt.Color(255, 255, 255));
        CourseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CourseBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CourseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CourseBtnMouseExited(evt);
            }
        });
        CourseBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crselbl.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        crselbl.setForeground(new java.awt.Color(255, 255, 255));
        crselbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/course_btn.png"))); // NOI18N
        crselbl.setText("Courses");
        CourseBtn.add(crselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        mainPnl1.add(CourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 205, 50));

        viewAllRecBtn.setBackground(new java.awt.Color(242, 203, 5));
        viewAllRecBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewAllRecBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewAllRecBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllRecBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewAllRecBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewAllRecBtnMouseExited(evt);
            }
        });
        viewAllRecBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/records_btn.png"))); // NOI18N
        jLabel16.setText("Records");
        viewAllRecBtn.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        mainPnl1.add(viewAllRecBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 205, 50));

        backBtn.setBackground(new java.awt.Color(242, 203, 5));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn.png"))); // NOI18N
        jLabel17.setText("Back");
        backBtn.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        mainPnl1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 205, 50));

        logoutBtn.setBackground(new java.awt.Color(242, 203, 5));
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        logoutBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout_btn.png"))); // NOI18N
        jLabel11.setText("Logout");
        logoutBtn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        mainPnl1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 205, 50));

        getContentPane().add(mainPnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 0, 240, 665));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
DefaultTableModel model;
//my methods..........................................................begin here
    private void searchCourse(){
     String query = "SELECT * FROM course";
     fmsConnection fc = new fmsConnection(query);
     try{
      ResultSet rs = fc.pStmt.executeQuery();
      while(rs.next()){
          String id = rs.getString("courseId");
          String name = rs.getString("courseName");
          String fees = rs.getString("courseFees");
          String duration = rs.getString("courseDuration");
//        String recieptNo = rs.getString("");
          Object obj[] = {id, name, fees, duration};
          model=(DefaultTableModel)tableCourse.getModel();
          model.addRow(obj);
     }
    }
    catch(Exception e){
        e.printStackTrace();
    }
    }
    
    public void clearTable(){
        DefaultTableModel model1 = (DefaultTableModel)tableCourse.getModel();
        model1.setRowCount(0);
    }
    
    private void updateDataIntoCourse(){
        String query = "UPDATE course SET courseName=?,courseFees=?,courseDuration=? WHERE courseId=?"; 
        fmsConnection fms = new fmsConnection(query); 
        
        try {
            fms.pStmt.setString(4,courseIdTxt.getText());
            fms.pStmt.setString(1,courseNameTxt.getText());
            fms.pStmt.setString(2,FeesTxt.getText());
          
            fms.pStmt.setString(3,durationTxt.getText());
            fms.pStmt.executeUpdate();
            JOptionPane.showMessageDialog(this,"data Updated..");
            clearTable();
            searchCourse();
            fms.con.close();
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this,"data Updation failed..");
        }
        
    }
    
    private void addDataIntoCourse(){
         String query = "INSERT INTO course (courseName,courseFees,courseDuration,courseId) VALUES(?,?,?,?)"; 
         fmsConnection fms = new fmsConnection(query); 
        
        try {
            fms.pStmt.setString(4,courseIdTxt.getText());
            fms.pStmt.setString(1,courseNameTxt.getText());
            fms.pStmt.setString(2,FeesTxt.getText());
          
            fms.pStmt.setString(3,durationTxt.getText());
            fms.pStmt.executeUpdate();
            JOptionPane.showMessageDialog(this,"data Inserted...");
            clearTable();
            searchCourse();
            fms.con.close();
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this,"data Insertion failed..");
        }
    }
    
    private void deleteDataFromCourse(){
         String query = "DELETE FROM course WHERE courseId=?"; 
         fmsConnection fms = new fmsConnection(query); 
        
        try {
            fms.pStmt.setString(1,courseIdTxt.getText());
//            fms.pStmt.setString(1,courseNameTxt.getText());
//            fms.pStmt.setString(2,FeesTxt.getText());
//          
//            fms.pStmt.setString(3,durationTxt.getText());
            fms.pStmt.executeUpdate();
            JOptionPane.showMessageDialog(this,"data deleted...");
            clearTable();
            searchCourse();
            fms.con.close();
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this,"data deletion failed..");
        }
    }
     // themes--------------------------------------------------------------------begin
    private void darkTheme(){
     
     mainPnl1.setBackground(new Color(128,128,128));
     mainPnl2.setBackground(new Color(64,64,64));
     homeBtn.setBackground(new Color(64,64,64)); 
     searchBtn.setBackground(new Color(64,64,64)); 
    
     CourseBtn.setBackground(new Color(64,64,64));
     viewAllRecBtn.setBackground(new Color(64,64,64));
     backBtn.setBackground(new Color(64,64,64)); 
     logoutBtn.setBackground(new Color(64,64,64)); 
     EditBtn.setBackground(new Color(64,64,64));
    }
    private void lightTheme(){
        
        mainPnl1.setBackground(new Color(242,135,5));
        mainPnl2.setBackground(new Color(242,159,100));
         homeBtn.setBackground(new Color(242,203,5));
       searchBtn.setBackground(new Color(242,203,5));
       CourseBtn.setBackground(new Color(242,203,5));
   viewAllRecBtn.setBackground(new Color(242,203,5));
         backBtn.setBackground(new Color(242,203,5));
       logoutBtn.setBackground(new Color(242,203,5)); 
    EditBtn.setBackground(new Color(242,203,5));
    
//        mainPnl1.setBackground(new Color(0, 204, 204));
//        mainPnl2.setBackground(new Color(0, 153, 153));
//        homeBtn.setBackground(new Color(0, 153, 153));
//        searehBtn.setBackground(new Color(0, 153, 153));
////        editCourseBtn.setBackground(new Color(0, 153, 153));
//        CourseBtn.setBackground(new Color(0, 153, 153));
//        viewAllRecBtn.setBackground(new Color(0, 153, 153));
//        backBtn.setBackground(new Color(0, 153, 153));
//        logoutBtn.setBackground(new Color(0, 153, 153)); 
    
    }
    
    private void courseIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseIdTxtActionPerformed

    private void courseIdTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_courseIdTxtKeyReleased
       
    }//GEN-LAST:event_courseIdTxtKeyReleased

    private void courseIdTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_courseIdTxtKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_courseIdTxtKeyTyped

    private void courseNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseNameTxtActionPerformed

    private void courseNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_courseNameTxtKeyReleased
        
    }//GEN-LAST:event_courseNameTxtKeyReleased

    private void FeesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FeesTxtActionPerformed

    private void FeesTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FeesTxtKeyReleased
        
    }//GEN-LAST:event_FeesTxtKeyReleased

    private void durationTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationTxtActionPerformed

    private void durationTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_durationTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_durationTxtKeyReleased

    private void durationTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_durationTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_durationTxtKeyTyped

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
       deleteDataFromCourse();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
    updateDataIntoCourse();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
       addDataIntoCourse();
    }//GEN-LAST:event_addBtnActionPerformed

    private void tableCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCourseMouseClicked
        int row = tableCourse.getSelectedRow();
        TableModel tModel = tableCourse.getModel();
        
        courseIdTxt.setText(tModel.getValueAt(row,0).toString());
        courseNameTxt.setText(tModel.getValueAt(row,1).toString());
        FeesTxt.setText(tModel.getValueAt(row,2).toString());
        durationTxt.setText(tModel.getValueAt(row,3).toString());
    }//GEN-LAST:event_tableCourseMouseClicked

    private void tableCourseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCourseMouseReleased

    }//GEN-LAST:event_tableCourseMouseReleased

    private void tableCourseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableCourseKeyReleased
       int row = tableCourse.getSelectedRow();
        TableModel tModel = tableCourse.getModel();
        
        courseIdTxt.setText(tModel.getValueAt(row,0).toString());
        courseNameTxt.setText(tModel.getValueAt(row,1).toString());
        FeesTxt.setText(tModel.getValueAt(row,2).toString());
        durationTxt.setText(tModel.getValueAt(row,3).toString());
    }//GEN-LAST:event_tableCourseKeyReleased

     //theme setCurrentTheme........................................................begin 2
    private void setCurrentTheme(String currentTheme){
        if(currentTheme.equalsIgnoreCase("dark")){
            selectDark();//here(in DB) true means dark theme
        }
        else{
            selectLight();//here(in DB) true means light theme
        }
    }
    //theme setCurrentTheme........................................................end
    
    // theme select.................................................................begin 3
    private void selectDark(){
        System.out.println("SelectDark");
        themeToggleButton.setText("Dark");
        themeToggleButton.setBackground(new Color(0, 0, 0));
        themeToggleButton.setForeground(new Color(255, 255, 255));
        darkTheme();
   
    }
    private void selectLight(){
         System.out.println("selectLight");
        themeToggleButton.setText("Light");
        themeToggleButton.setBackground(new Color(255, 255, 255));
        themeToggleButton.setForeground(new Color(0, 0, 0));
        lightTheme();
      
    }
    // theme select.................................................................end  3
    
    private void themeToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_themeToggleButtonItemStateChanged
        int state = evt.getStateChange();

        // if selectDark print dark theme in console
        if (state == java.awt.event.ItemEvent.SELECTED) {
            selectDark();
            Theme.setTheme("dark");
        }
        else { // else  print light theme theme in console
            selectLight();
            Theme.setTheme("light");
        }
    }//GEN-LAST:event_themeToggleButtonItemStateChanged

    private void themeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeToggleButtonActionPerformed

    }//GEN-LAST:event_themeToggleButtonActionPerformed

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.dispose();
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            homeBtn.setBackground(new Color(96, 96, 96));
        } else {
            homeBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            homeBtn.setBackground(new Color(64, 64, 64));
        } else {
            homeBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_homeBtnMouseExited

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        this.dispose();
        SearchRecord ad = new SearchRecord();
        ad.setVisible(true);
    }//GEN-LAST:event_searchBtnMouseClicked

    private void searchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            searchBtn.setBackground(new Color(96, 96, 96));
        } else {
            searchBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_searchBtnMouseEntered

    private void searchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            searchBtn.setBackground(new Color(64, 64, 64));
        } else {
            searchBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_searchBtnMouseExited

    private void EditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseClicked
        this.dispose();
        EditCourse ad = new EditCourse();
        ad.setVisible(true);
    }//GEN-LAST:event_EditBtnMouseClicked

    private void EditBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            EditBtn.setBackground(new Color(96, 96, 96));
        } else {
            EditBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_EditBtnMouseEntered

    private void EditBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            EditBtn.setBackground(new Color(64, 64, 64));
        } else {
            EditBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_EditBtnMouseExited

    private void CourseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseClicked
        this.dispose();
        AdminViewCourse ad = new AdminViewCourse();
        ad.setVisible(true);
    }//GEN-LAST:event_CourseBtnMouseClicked

    private void CourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            CourseBtn.setBackground(new Color(96, 96, 96));
        } else {
            CourseBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_CourseBtnMouseEntered

    private void CourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            CourseBtn.setBackground(new Color(64, 64, 64));
        } else {
            CourseBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_CourseBtnMouseExited

    private void viewAllRecBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllRecBtnMouseClicked
        this.dispose();
        ViewAllRecords ad = new ViewAllRecords();
        ad.setVisible(true);
    }//GEN-LAST:event_viewAllRecBtnMouseClicked

    private void viewAllRecBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllRecBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            viewAllRecBtn.setBackground(new Color(96, 96, 96));
        } else {
            viewAllRecBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_viewAllRecBtnMouseEntered

    private void viewAllRecBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllRecBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            viewAllRecBtn.setBackground(new Color(64, 64, 64));
        } else {
            viewAllRecBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_viewAllRecBtnMouseExited

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        this.dispose();
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
    }//GEN-LAST:event_backBtnMouseClicked

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            backBtn.setBackground(new Color(96, 96, 96));
        } else {
            backBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            backBtn.setBackground(new Color(64, 64, 64));
        } else {
            backBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_backBtnMouseExited

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        this.dispose();
        HomeMain ad = new HomeMain();
        ad.setVisible(true);
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            logoutBtn.setBackground(new Color(96, 96, 96));
        } else {
            logoutBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            logoutBtn.setBackground(new Color(64, 64, 64));
        } else {
            logoutBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_logoutBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CourseBtn;
    private javax.swing.JPanel EditBtn;
    private javax.swing.JTextField FeesTxt;
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel backBtn;
    private javax.swing.JTextField courseIdTxt;
    private javax.swing.JTextField courseNameTxt;
    private javax.swing.JLabel crselbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField durationTxt;
    private javax.swing.JPanel homeBtn;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JPanel mainPnl1;
    private javax.swing.JPanel mainPnl2;
    private javax.swing.JPanel searchBtn;
    private javax.swing.JTable tableCourse;
    private javax.swing.JToggleButton themeToggleButton;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel viewAllRecBtn;
    // End of variables declaration//GEN-END:variables
}
