/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Ravi_jaiswal
 */
public class FeesAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FeesAdmin
     */
    String currentTheme;
    public FeesAdmin() {
        
          this.setResizable(false);
        addTitleIcon();
        initComponents();
        gstTxt.setEditable(false);
        sGstTxt.setEditable(false);
        totalAmountTxt.setEditable(false);
        courseTxt.setEditable(false);
        selectedCashMethodByDefault();
        injectCourseIntoList();
        newRecieptNo();
        
        //theme settings..................................................begin 1
        currentTheme=Theme.getTheme();//fetching theme (previous theme selected)
        setCurrentTheme(currentTheme);
        //theme settings..................................................end
    }
    private void addTitleIcon(){
       
        
        ImageIcon icon = new ImageIcon("src/Images/college.png");
        this.setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPnl2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        recieptTxt = new javax.swing.JTextField();
        paymentOptionCombo = new javax.swing.JComboBox<>();
        Date1 = new com.toedter.calendar.JDateChooser();
        ddTxt = new javax.swing.JTextField();
        ddLbl = new javax.swing.JLabel();
        bankNameLbl = new javax.swing.JLabel();
        checkTxt = new javax.swing.JTextField();
        checkLbl = new javax.swing.JLabel();
        date_err_lbl = new javax.swing.JLabel();
        bankName_err_lbl = new javax.swing.JLabel();
        reciept_err_lbl = new javax.swing.JLabel();
        bankNameTxt = new javax.swing.JTextField();
        repoLogoLbl10 = new javax.swing.JLabel();
        repoLogoLbl14 = new javax.swing.JLabel();
        MainPnl1 = new javax.swing.JPanel();
        themeToggleButton = new javax.swing.JToggleButton();
        homeBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        EditBtn = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        CourseBtn = new javax.swing.JPanel();
        crselbl = new javax.swing.JLabel();
        viewAllRecBtn = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        backBtn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        repo_logo_small = new javax.swing.JLabel();
        mainPnl3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        recievedFromTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        startYearTxt = new com.toedter.calendar.JYearChooser();
        endYearTxt = new com.toedter.calendar.JYearChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        courseCombo = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        courseTxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarkTxt = new javax.swing.JTextArea();
        totalInWordsTxt = new javax.swing.JTextField();
        totalAmountTxt = new javax.swing.JTextField();
        sGstTxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        amountTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        printBtn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        amount_err_lbl2 = new javax.swing.JLabel();
        gstTxt = new javax.swing.JTextField();
        rollNoTxt = new javax.swing.JTextField();
        rollno_err_lbl = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        repo_logo_big = new javax.swing.JLabel();
        headerPnl = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("feesAdmin");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPnl2.setBackground(new java.awt.Color(242, 159, 100));
        MainPnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 204, 204));
        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Reciept no: FMT");
        MainPnl2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        jLabel9.setBackground(new java.awt.Color(0, 204, 204));
        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("Mode of Payment");
        MainPnl2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, -1));

        jLabel20.setBackground(new java.awt.Color(0, 204, 204));
        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 255, 255));
        jLabel20.setText("Date :");
        MainPnl2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 70, -1));

        jLabel21.setBackground(new java.awt.Color(0, 204, 204));
        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 255, 255));
        jLabel21.setText("GSTIN :     SJDKH4DJK");
        MainPnl2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 210, -1));

        recieptTxt.setEditable(false);
        recieptTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        recieptTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                recieptTxtKeyReleased(evt);
            }
        });
        MainPnl2.add(recieptTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 280, 30));

        paymentOptionCombo.setBackground(new java.awt.Color(242, 203, 5));
        paymentOptionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DD", "Check", "Cash", "Card" }));
        paymentOptionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentOptionComboActionPerformed(evt);
            }
        });
        MainPnl2.add(paymentOptionCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 180, 25));

        Date1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Date1KeyReleased(evt);
            }
        });
        MainPnl2.add(Date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 160, 25));

        ddTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MainPnl2.add(ddTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 280, 30));

        ddLbl.setBackground(new java.awt.Color(0, 204, 204));
        ddLbl.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        ddLbl.setForeground(new java.awt.Color(204, 255, 255));
        ddLbl.setText("DD no. : ");
        MainPnl2.add(ddLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        bankNameLbl.setBackground(new java.awt.Color(0, 204, 204));
        bankNameLbl.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        bankNameLbl.setForeground(new java.awt.Color(204, 255, 255));
        bankNameLbl.setText("Bank name:");
        MainPnl2.add(bankNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, -1));
        MainPnl2.add(checkTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 280, 30));

        checkLbl.setBackground(new java.awt.Color(0, 204, 204));
        checkLbl.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        checkLbl.setForeground(new java.awt.Color(204, 255, 255));
        checkLbl.setText("Check no. :");
        MainPnl2.add(checkLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, -1));

        date_err_lbl.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        date_err_lbl.setForeground(new java.awt.Color(255, 0, 51));
        MainPnl2.add(date_err_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 140, -1));

        bankName_err_lbl.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        bankName_err_lbl.setForeground(new java.awt.Color(255, 0, 51));
        MainPnl2.add(bankName_err_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 210, -1));

        reciept_err_lbl.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        reciept_err_lbl.setForeground(new java.awt.Color(255, 0, 0));
        MainPnl2.add(reciept_err_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 200, -1));

        bankNameTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bankNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankNameTxtActionPerformed(evt);
            }
        });
        bankNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bankNameTxtKeyReleased(evt);
            }
        });
        MainPnl2.add(bankNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 280, 30));

        repoLogoLbl10.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl10.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        MainPnl2.add(repoLogoLbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, -1));

        repoLogoLbl14.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl14.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        MainPnl2.add(repoLogoLbl14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(MainPnl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 1090, 190));

        MainPnl1.setBackground(new java.awt.Color(242, 135, 5));
        MainPnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        themeToggleButton.setBackground(new java.awt.Color(255, 255, 255));
        themeToggleButton.setText("Light");
        themeToggleButton.setFocusable(false);
        themeToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                themeToggleButtonItemStateChanged(evt);
            }
        });
        themeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeToggleButtonActionPerformed(evt);
            }
        });
        MainPnl1.add(themeToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 60, -1));

        homeBtn.setBackground(new java.awt.Color(242, 203, 5));
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Jokerman", 1, 26)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_btn.png"))); // NOI18N
        jLabel12.setText("Home");
        homeBtn.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        MainPnl1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 30, 230, 55));

        searchBtn.setBackground(new java.awt.Color(242, 203, 5));
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBtnMouseExited(evt);
            }
        });
        searchBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Jokerman", 1, 26)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_btn.png"))); // NOI18N
        jLabel13.setText("S Record");
        searchBtn.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        MainPnl1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 100, 230, 55));

        EditBtn.setBackground(new java.awt.Color(242, 203, 5));
        EditBtn.setForeground(new java.awt.Color(255, 255, 255));
        EditBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditBtnMouseExited(evt);
            }
        });
        EditBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Jokerman", 1, 26)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit_btn.png"))); // NOI18N
        jLabel14.setText("Edit Course");
        EditBtn.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        MainPnl1.add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 180, 230, 55));

        CourseBtn.setBackground(new java.awt.Color(242, 203, 5));
        CourseBtn.setForeground(new java.awt.Color(255, 255, 255));
        CourseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CourseBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CourseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CourseBtnMouseExited(evt);
            }
        });
        CourseBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crselbl.setFont(new java.awt.Font("Jokerman", 1, 26)); // NOI18N
        crselbl.setForeground(new java.awt.Color(255, 255, 255));
        crselbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/course_btn.png"))); // NOI18N
        crselbl.setText("Courses");
        CourseBtn.add(crselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        MainPnl1.add(CourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 250, 230, 55));

        viewAllRecBtn.setBackground(new java.awt.Color(242, 203, 5));
        viewAllRecBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewAllRecBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewAllRecBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllRecBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewAllRecBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewAllRecBtnMouseExited(evt);
            }
        });
        viewAllRecBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Jokerman", 1, 26)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/records_btn.png"))); // NOI18N
        jLabel16.setText("Records");
        viewAllRecBtn.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        MainPnl1.add(viewAllRecBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 330, 230, 55));

        backBtn.setBackground(new java.awt.Color(242, 203, 5));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Jokerman", 1, 26)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn.png"))); // NOI18N
        jLabel17.setText("Back");
        backBtn.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        MainPnl1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 400, 230, 55));

        logoutBtn.setBackground(new java.awt.Color(242, 203, 5));
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        logoutBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Jokerman", 1, 26)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout_btn.png"))); // NOI18N
        jLabel11.setText("Logout");
        logoutBtn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        MainPnl1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 480, 230, 55));

        repo_logo_small.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repo_logo_small.setForeground(new java.awt.Color(255, 255, 255));
        repo_logo_small.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence 3_1.png"))); // NOI18N
        MainPnl1.add(repo_logo_small, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        getContentPane().add(MainPnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 710));

        mainPnl3.setBackground(new java.awt.Color(242, 159, 100));
        mainPnl3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 204, 204));
        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("Recieved from");
        mainPnl3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, -1));

        recievedFromTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mainPnl3.add(recievedFromTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 5, 280, 32));

        jLabel6.setBackground(new java.awt.Color(0, 204, 204));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Roll No:");
        mainPnl3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 70, -1));

        jLabel19.setBackground(new java.awt.Color(0, 204, 204));
        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 255, 255));
        jLabel19.setText("The following payment in the college office for the year :");
        mainPnl3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 47, 470, -1));

        startYearTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startYearTxtMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                startYearTxtMouseReleased(evt);
            }
        });
        mainPnl3.add(startYearTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 47, -1, -1));
        mainPnl3.add(endYearTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 47, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 204, 204));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("to");
        mainPnl3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 47, 40, -1));

        jLabel18.setBackground(new java.awt.Color(0, 204, 204));
        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 255, 255));
        jLabel18.setText("Course :");
        mainPnl3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, -1));

        courseCombo.setBackground(new java.awt.Color(242, 203, 5));
        courseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboActionPerformed(evt);
            }
        });
        mainPnl3.add(courseCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 160, 25));

        jLabel24.setBackground(new java.awt.Color(0, 204, 204));
        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 255, 255));
        jLabel24.setText("Sr.No. :");
        mainPnl3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, 20));
        mainPnl3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 990, 10));
        mainPnl3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 990, 10));

        jLabel25.setBackground(new java.awt.Color(0, 204, 204));
        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 255, 255));
        jLabel25.setText("Heads :");
        mainPnl3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 60, -1));

        jLabel26.setBackground(new java.awt.Color(0, 204, 204));
        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 255, 255));
        jLabel26.setText("Amount(Rs) :");
        mainPnl3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 110, -1));

        courseTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mainPnl3.add(courseTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 311, 28));

        jLabel27.setBackground(new java.awt.Color(0, 204, 204));
        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 255, 255));
        jLabel27.setText("GST(9 %):");
        mainPnl3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 90, -1));

        jLabel28.setBackground(new java.awt.Color(0, 204, 204));
        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 255, 255));
        jLabel28.setText("SGST(9 %):");
        mainPnl3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 100, -1));

        jLabel22.setBackground(new java.awt.Color(0, 204, 204));
        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 255, 255));
        jLabel22.setText("Total in Words:");
        mainPnl3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, -1));

        jLabel29.setBackground(new java.awt.Color(242, 203, 5));
        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 255, 255));
        jLabel29.setText("Remark :");
        mainPnl3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 120, -1));

        remarkTxt.setColumns(20);
        remarkTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        remarkTxt.setRows(5);
        jScrollPane1.setViewportView(remarkTxt);

        mainPnl3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 310, 100));

        totalInWordsTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mainPnl3.add(totalInWordsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 311, 28));

        totalAmountTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mainPnl3.add(totalAmountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 220, 25));

        sGstTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mainPnl3.add(sGstTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 220, 25));
        mainPnl3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 280, 10));

        amountTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        amountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTxtActionPerformed(evt);
            }
        });
        amountTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountTxtKeyReleased(evt);
            }
        });
        mainPnl3.add(amountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 165, 220, 30));
        mainPnl3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 280, 10));

        jLabel30.setBackground(new java.awt.Color(0, 204, 204));
        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 255, 255));
        jLabel30.setText("Reciever Sign :");
        mainPnl3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, 140, -1));

        printBtn.setBackground(new java.awt.Color(0, 204, 51));
        printBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printBtn.setForeground(new java.awt.Color(255, 255, 255));
        printBtn.setText("print");
        printBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        mainPnl3.add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 170, 30));

        jLabel23.setBackground(new java.awt.Color(0, 204, 204));
        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 255, 255));
        jLabel23.setText("Recieved from");
        mainPnl3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, -1));

        amount_err_lbl2.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        amount_err_lbl2.setForeground(new java.awt.Color(255, 0, 51));
        mainPnl3.add(amount_err_lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 170, 150, -1));

        gstTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mainPnl3.add(gstTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 220, 25));

        rollNoTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        rollNoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rollNoTxtKeyReleased(evt);
            }
        });
        mainPnl3.add(rollNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 150, 27));

        rollno_err_lbl.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        rollno_err_lbl.setForeground(new java.awt.Color(255, 0, 0));
        mainPnl3.add(rollno_err_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 180, -1));

        jLabel32.setBackground(new java.awt.Color(0, 204, 204));
        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/about_1.png"))); // NOI18N
        mainPnl3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 460, -1, -1));

        repo_logo_big.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repo_logo_big.setForeground(new java.awt.Color(255, 255, 255));
        repo_logo_big.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence.png"))); // NOI18N
        mainPnl3.add(repo_logo_big, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        getContentPane().add(mainPnl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 1090, 520));

        headerPnl.setBackground(new java.awt.Color(242, 135, 5));
        headerPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setBackground(new java.awt.Color(0, 204, 204));
        jLabel31.setFont(new java.awt.Font("Jokerman", 1, 17)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("ADM!N");
        headerPnl.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, -1, -1));

        jLabel33.setBackground(new java.awt.Color(0, 204, 204));
        jLabel33.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hamburger.png"))); // NOI18N
        headerPnl.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel34.setBackground(new java.awt.Color(0, 204, 204));
        jLabel34.setFont(new java.awt.Font("Jokerman", 1, 17)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("MENU..");
        headerPnl.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 14, -1, -1));

        jLabel35.setBackground(new java.awt.Color(0, 204, 204));
        jLabel35.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 255, 255));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile.png"))); // NOI18N
        headerPnl.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, -1, -1));

        getContentPane().add(headerPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//....................................................................................................
    private void selectedCashMethodByDefault(){
    paymentOptionCombo.setSelectedIndex(2);
    }
    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {                                     
        
    }  
    private void paymentOptionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentOptionComboActionPerformed
      if(paymentOptionCombo.getSelectedIndex()==0){//dd
          checkLbl.setVisible(false);
          checkTxt.setVisible(false);
          ddLbl.setVisible(true);
          ddTxt.setVisible(true);
          bankNameLbl.setVisible(true);
          bankNameTxt.setVisible(true);
          
          //if change from one payment method to another text field should be clean from previous entered data
          ddTxt.setText("");
          bankNameTxt.setText("");
      }
      if(paymentOptionCombo.getSelectedIndex()==1){//check
          ddLbl.setVisible(false);
          ddTxt.setVisible(false);
          checkLbl.setVisible(true);
          checkTxt.setVisible(true);
          bankNameLbl.setVisible(true);
          bankNameTxt.setVisible(true);
          
          //if change from one payment method to another text field should be clean from previous entered data
          checkTxt.setText("");
          bankNameTxt.setText("");
      }
      if(paymentOptionCombo.getSelectedItem().toString().equals("Cash")){//Cash
          ddLbl.setVisible(false);
          ddTxt.setVisible(false);
          checkLbl.setVisible(false);
          checkTxt.setVisible(false);
          bankNameLbl.setVisible(false);
          bankNameTxt.setVisible(false);
          
          //if change from one payment method to another text field should be clean from previous entered data
          
          bankNameTxt.setText("");
      }
      if(paymentOptionCombo.getSelectedIndex()==3){//Card
          ddLbl.setVisible(false);
          ddTxt.setVisible(false);
          checkLbl.setVisible(false);
          checkTxt.setVisible(false);
          bankNameLbl.setVisible(true);
          bankNameTxt.setVisible(true);
      }
    }//GEN-LAST:event_paymentOptionComboActionPerformed
    //My methods......................................................................................
    String recieptNo,bankName,dd_no,check_no,recieved_from,amount,roll_no;
    Date date;
    private boolean flag[]=new boolean[4];
   
    public boolean myValidate(){//my validate function...........................
         flag[0]=true;
         flag[1]=true;
         recieptNo=recieptTxt.getText();
         date=Date1.getDate();
         check_no=checkTxt.getText();
         dd_no=ddTxt.getText();
         bankName=bankNameTxt.getText();
         recieved_from=recievedFromTxt.getText();
         roll_no=rollNoTxt.getText();
         amount=amountTxt.getText();
         
         return checkEmptyField()&&flagResult(); 
    }
    
    private boolean flagResult(){
        boolean res=true;
        for (boolean b : flag) {
           res=res&&b; 
           System.out.println(b);
           System.out.println(res+":res---------");
        }
        System.out.println("final result"+res);
        return res;
    }
    
    public boolean checkEmptyField(){//check for empty fields..............................
        if(recieptNo.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Reciept no.!");
        return false;
        }
        if(date==null){
            JOptionPane.showMessageDialog(this, "please Select Date!");
            System.out.println("date..................."+date);
        return false;
        }
        if(paymentOptionCombo.getSelectedItem().equals("Check")){
            if( check_no.equals("")){
                JOptionPane.showMessageDialog(this, "please Enter check no.!");
                 return false;
            }
            if( bankName.equals("")){
                JOptionPane.showMessageDialog(this, "please Enter Bank Name!");
                 return false;
            }
        }
        if(paymentOptionCombo.getSelectedItem().equals("DD")){
            if( dd_no.equals("")){
                JOptionPane.showMessageDialog(this, "please Enter DD no.!");
                 return false;
            }
            if( bankName.equals("")){
                JOptionPane.showMessageDialog(this, "please Enter Bank Name!");
                 return false;
            }
        }
        if(paymentOptionCombo.getSelectedItem().equals("Card")){
            
            if( bankName.equals("")){
                JOptionPane.showMessageDialog(this, "please Enter Bank Name!");
                 return false;
            }
        }
        if(recieved_from.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Recieved from.!");
        return false;
        }
        
        if(roll_no.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Roll no.!");
        return false;
        }
        
        if(amount.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Amount!");
        return false;
        }
        
     return true;
    }
    
   
    
//    public void reset(){
//        fNameTxt.setText("");
//        lNameTxt.setText("");
//        uNameTxt.setText("");
//        passTxt.setText("");
//        confPassTxt.setText("");
//        dobTxt.setDate(null);
//        contTxt.setText("");
//    }
    
    public boolean patternMatcher1(String regex,String name){
    Pattern p = Pattern.compile(regex); 
    Matcher m= p.matcher(name);
    return m.find();
    }
    
    private void injectCourseIntoList() {//fetchiching courses from table and add data into course combo......
        String query="SELECT * FROM course";
        fmsConnection con = new fmsConnection(query);
        
        try {
            ResultSet rs= con.pStmt.executeQuery();
            while(rs.next()){
               courseCombo.addItem(rs.getString("courseName"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FeesAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void newRecieptNo(){
    String query = "SELECT MAX(reciept_no) from fees";    
    fmsConnection con1 = new fmsConnection(query);
        try {
            ResultSet rs = con1.pStmt.executeQuery();
                 if(rs.next()) {                    
                    int max =rs.getInt(1);
                    recieptTxt.setText(String.valueOf(max+1)); 
                }
            con1.con.close();
        } catch (SQLException ex) {
            Logger.getLogger(FeesAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private boolean insertDataIntoDb(){
        //to convert default date format into yyyy-MM-dd format
         //note month must be MM not mm
         System.out.println("beforedate");
        SimpleDateFormat dateFormat1= new SimpleDateFormat("yyyy-MM-dd");
         System.out.println("Betweendate");
        String date2=dateFormat1.format(Date1.getDate());
        System.out.println("Afterdate");
        
        String forYear=String.valueOf(startYearTxt.getYear())+"to"+String.valueOf(endYearTxt.getYear());
//        String forYear="correct it!";
//        System.out.println("forYear............"+forYear);
        
        String query ="insert into fees(reciept_no,check_no,bank_name,date,recieved_from,roll_no,course,total_amount,remark,payment_mode,dd_no,start_year,end_year,amount,sgst,gst,Ttl_in_words)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        fmsConnection fc = new fmsConnection(query);
          
            
        try{
            fc.pStmt.setString(1,recieptTxt.getText());
            fc.pStmt.setString(2,checkTxt.getText());
            fc.pStmt.setString(3,bankNameTxt.getText());
          
            fc.pStmt.setString(4,date2);
           
            fc.pStmt.setString(5,recievedFromTxt.getText());
            fc.pStmt.setInt(6, Integer.parseInt(rollNoTxt.getText()));
          
            fc.pStmt.setString(7, courseTxt.getText());
            fc.pStmt.setInt(8, (int)Float.parseFloat(totalAmountTxt.getText()));
            fc.pStmt.setString(9, remarkTxt.getText());
            fc.pStmt.setString(10, paymentOptionCombo.getSelectedItem().toString());
            fc.pStmt.setString(11,ddTxt.getText() );
            
            fc.pStmt.setInt(12,startYearTxt.getYear() );
            fc.pStmt.setInt(13,endYearTxt.getYear() );
            fc.pStmt.setInt(14,Integer.parseInt(amountTxt.getText()));
            fc.pStmt.setString(15,sGstTxt.getText() );
            fc.pStmt.setString(16,gstTxt.getText() );
            fc.pStmt.setString(17,totalInWordsTxt.getText());
            
           

            fc.pStmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Inserted Successfull...");
            fc.con.close();
            return true;
        }
        catch(Exception e){
            System.out.println("Signup failed.");
            e.printStackTrace();
             return false;
        }
        
    }
    
    private void darkTheme(){
     headerPnl.setBackground(new Color(128,128,128));
     
     printBtn.setBackground(new Color(128,128,128));
     MainPnl1.setBackground(new Color(128,128,128));
     MainPnl2.setBackground(new Color(64,64,64));
     mainPnl3.setBackground(new Color(64,64,64)); 
     homeBtn.setBackground(new Color(64,64,64)); 
     searchBtn.setBackground(new Color(64,64,64)); 
     EditBtn.setBackground(new Color(64,64,64)); 
     CourseBtn.setBackground(new Color(64,64,64));
     viewAllRecBtn.setBackground(new Color(64,64,64));
     backBtn.setBackground(new Color(64,64,64)); 
     logoutBtn.setBackground(new Color(64,64,64)); 
    
    }
    private void lightTheme(){
        
     headerPnl.setBackground(new Color(242,135,5));
     printBtn.setBackground(new Color(0,204,51));
     MainPnl1.setBackground(new Color(242,135,5));
     MainPnl2.setBackground(new Color(242,159,100));
     mainPnl3.setBackground(new Color(242,159,100)); 
      homeBtn.setBackground(new Color(242,203,5)); 
    searchBtn.setBackground(new Color(242,203,5)); 
      EditBtn.setBackground(new Color(242,203,5)); 
    CourseBtn.setBackground(new Color(242,203,5));
viewAllRecBtn.setBackground(new Color(242,203,5));
      backBtn.setBackground(new Color(242,203,5)); 
    logoutBtn.setBackground(new Color(242,203,5)); 
    
    }
    //ends here...........................
    
    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        if(myValidate()){
            System.out.println("Validation done...");
            if(insertDataIntoDb()){
                this.dispose();
                AReciept reciept= new AReciept();
                reciept.setVisible(true);
            }
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void themeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeToggleButtonActionPerformed
    
    }//GEN-LAST:event_themeToggleButtonActionPerformed

     //theme setCurrentTheme........................................................begin 2
    private void setCurrentTheme(String currentTheme){
        if(currentTheme.equalsIgnoreCase("dark")){
            selectDark();//here(in DB) true means dark theme
        }
        else{
            selectLight();//here(in DB) true means light theme
        }
    }
    //theme setCurrentTheme........................................................end
    
    // theme select.................................................................begin 3
    private void selectDark(){
        System.out.println("SelectDark");
        themeToggleButton.setText("Dark");
        themeToggleButton.setBackground(new Color(0, 0, 0));
        themeToggleButton.setForeground(new Color(255, 255, 255));
        darkTheme();
   
    }
    private void selectLight(){
         System.out.println("selectLight");
        themeToggleButton.setText("Light");
        themeToggleButton.setBackground(new Color(255, 255, 255));
        themeToggleButton.setForeground(new Color(0, 0, 0));
        lightTheme();
      
    }
    // theme select.................................................................end  3
    
    private void themeToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_themeToggleButtonItemStateChanged
         int state = evt.getStateChange();
 
                // if selectDark print dark theme in console
                if (state == java.awt.event.ItemEvent.SELECTED) {
                    selectDark();
                    Theme.setTheme("dark");//to Db
                }
                else { // else  print light theme theme in console
                     selectLight();
                    Theme.setTheme("light");
                }
    }//GEN-LAST:event_themeToggleButtonItemStateChanged

    private void Date1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Date1KeyReleased
     
    }//GEN-LAST:event_Date1KeyReleased

    private void recieptTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recieptTxtKeyReleased
//        if(patternMatcher1("^[1-9][0-9]*$",recieptTxt.getText())){
//            reciept_err_lbl.setText("");
//             flag[2]=true;
//        }
//        else{
//            reciept_err_lbl.setText("*invalid reciept no.)");
//             flag[2]=true;
//        }
    }//GEN-LAST:event_recieptTxtKeyReleased

    private void amountTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountTxtKeyReleased
       if(patternMatcher1("^[1-9][0-9]*$",amountTxt.getText())){
            amount_err_lbl2.setText("");
             flag[3]=true;
        }
        else{
            amount_err_lbl2.setText("numbers only*");
             flag[3]=false;
        }
    }//GEN-LAST:event_amountTxtKeyReleased

    private void bankNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bankNameTxtKeyReleased
       
    }//GEN-LAST:event_bankNameTxtKeyReleased

    private void rollNoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollNoTxtKeyReleased
        if(patternMatcher1("^[1-9][0-9]*$",rollNoTxt.getText())){
            rollno_err_lbl.setText("");
             flag[2]=true;
        }
        else{
            rollno_err_lbl.setText("numbers only*");
             flag[2]=false;
        }
    }//GEN-LAST:event_rollNoTxtKeyReleased

    private void amountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTxtActionPerformed
       if(amount_err_lbl2.getText().equals("")){
        float tax;
       float netAmount;
       int amount1=Integer.parseInt(amountTxt.getText());
       tax=(0.09f)*amount1;
       gstTxt.setText(String.valueOf(tax));
       sGstTxt.setText(String.valueOf(tax));
       netAmount=amount1+tax+tax;
       totalAmountTxt.setText(String.valueOf(netAmount));
       
       //converting netAmount into integer and then pass value to convert
       String word= NumberToWordsConverter.convert((int)netAmount);
       totalInWordsTxt.setText(word+" only.");
       }
       else{
       gstTxt.setText("");
       sGstTxt.setText("");
       totalAmountTxt.setText("");
       }
    }//GEN-LAST:event_amountTxtActionPerformed

    private void courseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboActionPerformed
        String course;
        course =courseCombo.getSelectedItem().toString();
        courseTxt.setText(course);
    }//GEN-LAST:event_courseComboActionPerformed

    private void startYearTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startYearTxtMouseClicked
       
    }//GEN-LAST:event_startYearTxtMouseClicked

    private void startYearTxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startYearTxtMouseReleased
      
    }//GEN-LAST:event_startYearTxtMouseReleased

    private void bankNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankNameTxtActionPerformed
       
    }//GEN-LAST:event_bankNameTxtActionPerformed

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.dispose();
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
         
    }//GEN-LAST:event_homeBtnMouseClicked

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        this.dispose();
       SearchRecord ad = new SearchRecord();
        ad.setVisible(true);
    }//GEN-LAST:event_searchBtnMouseClicked

    private void EditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseClicked
        this.dispose();
       EditCourse ad = new EditCourse();
        ad.setVisible(true);
    }//GEN-LAST:event_EditBtnMouseClicked

    private void CourseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseClicked
        this.dispose();
       AdminViewCourse ad = new AdminViewCourse();
        ad.setVisible(true);
    }//GEN-LAST:event_CourseBtnMouseClicked

    private void viewAllRecBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllRecBtnMouseClicked
        this.dispose();
       ViewAllRecords ad = new ViewAllRecords();
        ad.setVisible(true);
    }//GEN-LAST:event_viewAllRecBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
      this.dispose();
       AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
        
    }//GEN-LAST:event_backBtnMouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
       this.dispose();
       HomeMain ad = new HomeMain();
        ad.setVisible(true);
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
       if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            homeBtn.setBackground(new Color(96, 96, 96));
        } else {
            homeBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_homeBtnMouseEntered

    private void searchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseEntered
       if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            searchBtn.setBackground(new Color(96, 96, 96));
        } else {
            searchBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_searchBtnMouseEntered

    private void EditBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseEntered
       if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            EditBtn.setBackground(new Color(96, 96, 96));
        } else {
            EditBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_EditBtnMouseEntered

    private void CourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseEntered
       if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            CourseBtn.setBackground(new Color(96, 96, 96));
        } else {
            CourseBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_CourseBtnMouseEntered

    private void viewAllRecBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllRecBtnMouseEntered
       if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            viewAllRecBtn.setBackground(new Color(96, 96, 96));
        } else {
            viewAllRecBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_viewAllRecBtnMouseEntered

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
       if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            backBtn.setBackground(new Color(96, 96, 96));
        } else {
            backBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_backBtnMouseEntered

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
       if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            logoutBtn.setBackground(new Color(96, 96, 96));
        } else {
            logoutBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
       if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            homeBtn.setBackground(new Color(64, 64, 64));
        } else {
            homeBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_homeBtnMouseExited

    private void searchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseExited
       if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            searchBtn.setBackground(new Color(64, 64, 64));
        } else {
            searchBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_searchBtnMouseExited

    private void EditBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseExited
       if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            EditBtn.setBackground(new Color(64, 64, 64));
        } else {
            EditBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_EditBtnMouseExited

    private void CourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseExited
       if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            CourseBtn.setBackground(new Color(64, 64, 64));
        } else {
            CourseBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_CourseBtnMouseExited

    private void viewAllRecBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllRecBtnMouseExited
       if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            viewAllRecBtn.setBackground(new Color(64, 64, 64));
        } else {
            viewAllRecBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_viewAllRecBtnMouseExited

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
       if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            backBtn.setBackground(new Color(64, 64, 64));
        } else {
            backBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_backBtnMouseExited

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
       if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            logoutBtn.setBackground(new Color(64, 64, 64));
        } else {
            logoutBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_logoutBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeesAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CourseBtn;
    private com.toedter.calendar.JDateChooser Date1;
    private javax.swing.JPanel EditBtn;
    private javax.swing.JPanel MainPnl1;
    private javax.swing.JPanel MainPnl2;
    private javax.swing.JTextField amountTxt;
    private javax.swing.JLabel amount_err_lbl2;
    private javax.swing.JPanel backBtn;
    private javax.swing.JLabel bankNameLbl;
    private javax.swing.JTextField bankNameTxt;
    private javax.swing.JLabel bankName_err_lbl;
    private javax.swing.JLabel checkLbl;
    private javax.swing.JTextField checkTxt;
    private javax.swing.JComboBox<String> courseCombo;
    private javax.swing.JTextField courseTxt;
    private javax.swing.JLabel crselbl;
    private javax.swing.JLabel date_err_lbl;
    private javax.swing.JLabel ddLbl;
    private javax.swing.JTextField ddTxt;
    private com.toedter.calendar.JYearChooser endYearTxt;
    private javax.swing.JTextField gstTxt;
    private javax.swing.JPanel headerPnl;
    private javax.swing.JPanel homeBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JPanel mainPnl3;
    private javax.swing.JComboBox<String> paymentOptionCombo;
    private javax.swing.JButton printBtn;
    private javax.swing.JTextField recieptTxt;
    private javax.swing.JLabel reciept_err_lbl;
    private javax.swing.JTextField recievedFromTxt;
    private javax.swing.JTextArea remarkTxt;
    private javax.swing.JLabel repoLogoLbl10;
    private javax.swing.JLabel repoLogoLbl14;
    private javax.swing.JLabel repo_logo_big;
    private javax.swing.JLabel repo_logo_small;
    private javax.swing.JTextField rollNoTxt;
    private javax.swing.JLabel rollno_err_lbl;
    private javax.swing.JTextField sGstTxt;
    private javax.swing.JPanel searchBtn;
    private com.toedter.calendar.JYearChooser startYearTxt;
    private javax.swing.JToggleButton themeToggleButton;
    private javax.swing.JTextField totalAmountTxt;
    private javax.swing.JTextField totalInWordsTxt;
    private javax.swing.JPanel viewAllRecBtn;
    // End of variables declaration//GEN-END:variables

    
}
