/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import javax.swing.ImageIcon;

/**
 *
 * @author Ravi_jaiswal
 */
public class HomeMain extends javax.swing.JFrame {

    /**
     * Creates new form HomeMain
     */
    public HomeMain() {
          this.setResizable(false);
        initComponents();
        addTitleIcon();
    }
    private void addTitleIcon(){
        ImageIcon icon = new ImageIcon("src/Images/college.png");
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main2kGradientPanel2 = new keeptoo.KGradientPanel();
        repoLogoLbl = new javax.swing.JLabel();
        repoLogoLbl1 = new javax.swing.JLabel();
        repoLogoLbl2 = new javax.swing.JLabel();
        repoLogoLbl5 = new javax.swing.JLabel();
        repoLogoLbl7 = new javax.swing.JLabel();
        repoLogoLbl8 = new javax.swing.JLabel();
        repoLogoLbl11 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JLabel();
        repoLogoLbl15 = new javax.swing.JLabel();
        repoLogoLbl16 = new javax.swing.JLabel();
        repoLogoLbl17 = new javax.swing.JLabel();
        repoLogoLbl18 = new javax.swing.JLabel();
        repoLogoLbl21 = new javax.swing.JLabel();
        studentBtnK = new keeptoo.KGradientPanel();
        studentBtnp = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        adminBtnK1 = new keeptoo.KGradientPanel();
        adminBtnKp = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        repoLogoLbl19 = new javax.swing.JLabel();
        repoLogoLbl6 = new javax.swing.JLabel();
        repoLogoLbl12 = new javax.swing.JLabel();
        repoLogoLbl14 = new javax.swing.JLabel();
        repoLogoLbl23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        repoLogoLbl3 = new javax.swing.JLabel();
        repoLogoLbl4 = new javax.swing.JLabel();
        repoLogoLbl24 = new javax.swing.JLabel();
        repoLogoLbl25 = new javax.swing.JLabel();
        repoLogoLbl26 = new javax.swing.JLabel();
        repoLogoLbl28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login page...");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main2kGradientPanel2.setkEndColor(new java.awt.Color(255, 153, 51));
        main2kGradientPanel2.setkGradientFocus(1000);
        main2kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 204));
        main2kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        repoLogoLbl.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence.png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, -1, -1));

        repoLogoLbl1.setFont(new java.awt.Font("Jokerman", 0, 30)); // NOI18N
        repoLogoLbl1.setForeground(new java.awt.Color(204, 204, 0));
        repoLogoLbl1.setText("Login As :");
        main2kGradientPanel2.add(repoLogoLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 150, 40));

        repoLogoLbl2.setFont(new java.awt.Font("Jokerman", 0, 40)); // NOI18N
        repoLogoLbl2.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl2.setText("FEES   MANAGEMENT   SYSTEM");
        main2kGradientPanel2.add(repoLogoLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 490, 40));

        repoLogoLbl5.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl5.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence.png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        repoLogoLbl7.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl7.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, 120));

        repoLogoLbl8.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl8.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/about_1.png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 710, -1, 50));

        repoLogoLbl11.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl11.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, 120));

        exitBtn.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/turn-off.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });
        main2kGradientPanel2.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        repoLogoLbl15.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl15.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 90, 60));

        repoLogoLbl16.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl16.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/graph.png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 140, 140));

        repoLogoLbl17.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl17.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/university.png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, -1));

        repoLogoLbl18.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl18.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl18, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, -30, -1, 120));

        repoLogoLbl21.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl21.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/about_1.png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 710, -1, 50));

        studentBtnK.setkEndColor(new java.awt.Color(51, 51, 255));
        studentBtnK.setkGradientFocus(200);
        studentBtnK.setkStartColor(new java.awt.Color(235, 0, 19));
        studentBtnK.setPreferredSize(new java.awt.Dimension(900, 80));
        studentBtnK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentBtnp.setOpaque(false);
        studentBtnp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentBtnpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentBtnpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentBtnpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout studentBtnpLayout = new javax.swing.GroupLayout(studentBtnp);
        studentBtnp.setLayout(studentBtnpLayout);
        studentBtnpLayout.setHorizontalGroup(
            studentBtnpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        studentBtnpLayout.setVerticalGroup(
            studentBtnpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        studentBtnK.add(studentBtnp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("STUDENT");
        studentBtnK.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        main2kGradientPanel2.add(studentBtnK, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 170, 50));

        adminBtnK1.setkEndColor(new java.awt.Color(51, 51, 255));
        adminBtnK1.setkGradientFocus(200);
        adminBtnK1.setkStartColor(new java.awt.Color(235, 0, 19));
        adminBtnK1.setPreferredSize(new java.awt.Dimension(900, 80));
        adminBtnK1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminBtnKp.setOpaque(false);
        adminBtnKp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminBtnKpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminBtnKpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminBtnKpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout adminBtnKpLayout = new javax.swing.GroupLayout(adminBtnKp);
        adminBtnKp.setLayout(adminBtnKpLayout);
        adminBtnKpLayout.setHorizontalGroup(
            adminBtnKpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        adminBtnKpLayout.setVerticalGroup(
            adminBtnKpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        adminBtnK1.add(adminBtnKp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ADMIN");
        adminBtnK1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 10, -1, -1));

        main2kGradientPanel2.add(adminBtnK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 170, 50));

        repoLogoLbl19.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl19.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/university.png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, -1, -1));

        repoLogoLbl6.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl6.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1).png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 220, -1, -1));

        repoLogoLbl12.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl12.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1).png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, -20, -1, -1));

        repoLogoLbl14.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl14.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, -150, 250, 270));

        repoLogoLbl23.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl23.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -150, 250, 270));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/design-thinking.png"))); // NOI18N
        main2kGradientPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 130, 277, 280));

        repoLogoLbl3.setFont(new java.awt.Font("Jokerman", 0, 30)); // NOI18N
        repoLogoLbl3.setForeground(new java.awt.Color(0, 204, 204));
        repoLogoLbl3.setText("WELCOME TO");
        main2kGradientPanel2.add(repoLogoLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 220, 40));

        repoLogoLbl4.setFont(new java.awt.Font("Jokerman", 0, 30)); // NOI18N
        repoLogoLbl4.setForeground(new java.awt.Color(204, 204, 0));
        repoLogoLbl4.setText("Login As :");
        main2kGradientPanel2.add(repoLogoLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 150, 40));

        repoLogoLbl24.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl24.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/college.png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 70));

        repoLogoLbl25.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl25.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl25, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 70, 60));

        repoLogoLbl26.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl26.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 70, 60));

        repoLogoLbl28.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl28.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        main2kGradientPanel2.add(repoLogoLbl28, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 70, 60));

        getContentPane().add(main2kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 665));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentBtnpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentBtnpMouseEntered
        studentBtnK.setLocation(studentBtnK.getX()+5, studentBtnK.getY()+5);
    }//GEN-LAST:event_studentBtnpMouseEntered

    private void studentBtnpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentBtnpMouseExited
        studentBtnK.setLocation(studentBtnK.getX()-5, studentBtnK.getY()-5);
    }//GEN-LAST:event_studentBtnpMouseExited

    private void adminBtnKpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBtnKpMouseEntered
        adminBtnK1.setLocation(adminBtnK1.getX()+5, adminBtnK1.getY()+5);
    }//GEN-LAST:event_adminBtnKpMouseEntered

    private void adminBtnKpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBtnKpMouseExited
       adminBtnK1.setLocation(adminBtnK1.getX()-5, adminBtnK1.getY()-5);
    }//GEN-LAST:event_adminBtnKpMouseExited

    private void studentBtnpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentBtnpMouseClicked
        this.dispose();
        StudentLogin login = new StudentLogin();
        login.setVisible(true);
    }//GEN-LAST:event_studentBtnpMouseClicked

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
      exitBtn.setLocation(exitBtn.getX()-2, exitBtn.getY()-2);
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        exitBtn.setLocation(exitBtn.getX()+2, exitBtn.getY()+2);
    }//GEN-LAST:event_exitBtnMouseExited

    private void adminBtnKpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBtnKpMouseClicked
        this.dispose();
        AdminLogin login = new AdminLogin();
        login.setVisible(true);
    }//GEN-LAST:event_adminBtnKpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel adminBtnK1;
    private javax.swing.JPanel adminBtnKp;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private keeptoo.KGradientPanel main2kGradientPanel2;
    private javax.swing.JLabel repoLogoLbl;
    private javax.swing.JLabel repoLogoLbl1;
    private javax.swing.JLabel repoLogoLbl11;
    private javax.swing.JLabel repoLogoLbl12;
    private javax.swing.JLabel repoLogoLbl14;
    private javax.swing.JLabel repoLogoLbl15;
    private javax.swing.JLabel repoLogoLbl16;
    private javax.swing.JLabel repoLogoLbl17;
    private javax.swing.JLabel repoLogoLbl18;
    private javax.swing.JLabel repoLogoLbl19;
    private javax.swing.JLabel repoLogoLbl2;
    private javax.swing.JLabel repoLogoLbl21;
    private javax.swing.JLabel repoLogoLbl23;
    private javax.swing.JLabel repoLogoLbl24;
    private javax.swing.JLabel repoLogoLbl25;
    private javax.swing.JLabel repoLogoLbl26;
    private javax.swing.JLabel repoLogoLbl28;
    private javax.swing.JLabel repoLogoLbl3;
    private javax.swing.JLabel repoLogoLbl4;
    private javax.swing.JLabel repoLogoLbl5;
    private javax.swing.JLabel repoLogoLbl6;
    private javax.swing.JLabel repoLogoLbl7;
    private javax.swing.JLabel repoLogoLbl8;
    private keeptoo.KGradientPanel studentBtnK;
    private javax.swing.JPanel studentBtnp;
    // End of variables declaration//GEN-END:variables
}
