/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ravi_jaiswal
 */

public class Report extends javax.swing.JFrame {
 String currentTheme;
    /**
     * Creates new form Report
     */
    public Report() {
          this.setResizable(false);
        addTitleIcon();
        initComponents();
        injectCourseIntoList();
         //theme settings..................................................begin 1
        currentTheme=Theme.getTheme();
        setCurrentTheme(currentTheme);
        //theme settings..................................................end
    }
    private void addTitleIcon(){
        ImageIcon icon = new ImageIcon("src/Images/college.png");
        this.setIconImage(icon.getImage());
    }
     private void injectCourseIntoList() {//fetchiching courses from table and add data into course combo......
        String query="SELECT * FROM course";
        fmsConnection con = new fmsConnection(query);
        
        try {
            ResultSet rs= con.pStmt.executeQuery();
            while(rs.next()){
               courseCombo.addItem(rs.getString("courseName"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FeesAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPnl1 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        repoLogoLbl = new javax.swing.JLabel();
        themeToggleButton = new javax.swing.JToggleButton();
        homeBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        EditBtn = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        CourseBtn = new javax.swing.JPanel();
        crselbl = new javax.swing.JLabel();
        viewAllRecBtn = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        backBtn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        mainPnl2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFees = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        amountLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        courseCombo = new javax.swing.JComboBox<>();
        endDate = new com.toedter.calendar.JDateChooser();
        staartDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalAmntInWordLbl = new javax.swing.JLabel();
        courseSlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reports");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPnl1.setBackground(new java.awt.Color(242, 135, 5));
        MainPnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        MainPnl1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 150, 10));

        jLabel15.setFont(new java.awt.Font("Jokerman", 0, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/view all record.png"))); // NOI18N
        MainPnl1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 70));

        repoLogoLbl.setFont(new java.awt.Font("Jokerman", 0, 30)); // NOI18N
        repoLogoLbl.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl.setText(" REPORTS");
        MainPnl1.add(repoLogoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 150, 30));

        themeToggleButton.setBackground(new java.awt.Color(255, 255, 255));
        themeToggleButton.setText("Light");
        themeToggleButton.setFocusable(false);
        themeToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                themeToggleButtonItemStateChanged(evt);
            }
        });
        themeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeToggleButtonActionPerformed(evt);
            }
        });
        MainPnl1.add(themeToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 60, -1));

        homeBtn.setBackground(new java.awt.Color(242, 203, 5));
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_btn.png"))); // NOI18N
        jLabel12.setText("Home");
        homeBtn.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        MainPnl1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 205, 50));

        searchBtn.setBackground(new java.awt.Color(242, 203, 5));
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBtnMouseExited(evt);
            }
        });
        searchBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_btn.png"))); // NOI18N
        jLabel13.setText("S Record");
        searchBtn.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        MainPnl1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 205, 50));

        EditBtn.setBackground(new java.awt.Color(242, 203, 5));
        EditBtn.setForeground(new java.awt.Color(255, 255, 255));
        EditBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditBtnMouseExited(evt);
            }
        });
        EditBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit_btn.png"))); // NOI18N
        jLabel14.setText("Edit Course");
        EditBtn.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        MainPnl1.add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 205, 50));

        CourseBtn.setBackground(new java.awt.Color(242, 203, 5));
        CourseBtn.setForeground(new java.awt.Color(255, 255, 255));
        CourseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CourseBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CourseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CourseBtnMouseExited(evt);
            }
        });
        CourseBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crselbl.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        crselbl.setForeground(new java.awt.Color(255, 255, 255));
        crselbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/course_btn.png"))); // NOI18N
        crselbl.setText("Courses");
        CourseBtn.add(crselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        MainPnl1.add(CourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 205, 50));

        viewAllRecBtn.setBackground(new java.awt.Color(242, 203, 5));
        viewAllRecBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewAllRecBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewAllRecBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllRecBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewAllRecBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewAllRecBtnMouseExited(evt);
            }
        });
        viewAllRecBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/records_btn.png"))); // NOI18N
        jLabel16.setText("Records");
        viewAllRecBtn.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        MainPnl1.add(viewAllRecBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 205, 50));

        backBtn.setBackground(new java.awt.Color(242, 203, 5));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn.png"))); // NOI18N
        jLabel17.setText("Back");
        backBtn.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        MainPnl1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 205, 50));

        logoutBtn.setBackground(new java.awt.Color(242, 203, 5));
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        logoutBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout_btn.png"))); // NOI18N
        jLabel11.setText("Logout");
        logoutBtn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        MainPnl1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 205, 50));

        getContentPane().add(MainPnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 665));

        mainPnl2.setBackground(new java.awt.Color(242, 159, 100));
        mainPnl2.setAutoscrolls(true);
        mainPnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableFees.setBackground(new java.awt.Color(153, 153, 255));
        tableFees.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tableFees.setForeground(new java.awt.Color(255, 255, 255));
        tableFees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RecieptNo.", "RollNo.", "StudentName", "Course", "Amount", "Remark", "date"
            }
        ));
        jScrollPane1.setViewportView(tableFees);

        mainPnl2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 100, 920, 390));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("To :");
        mainPnl2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        amountLbl.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        amountLbl.setForeground(new java.awt.Color(255, 204, 204));
        mainPnl2.add(amountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 180, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Date :");
        mainPnl2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));
        mainPnl2.add(courseCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 300, 20));
        mainPnl2.add(endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 130, -1));
        mainPnl2.add(staartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 130, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setText("Export to Exel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainPnl2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 110, 20));

        submitBtn.setBackground(new java.awt.Color(0, 204, 0));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        mainPnl2.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 90, 20));

        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        mainPnl2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 90, 20));

        jButton4.setText("Browse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        mainPnl2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 90, 20));
        mainPnl2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 320, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select Course :");
        mainPnl2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Course Selected :");
        mainPnl2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total amount collected :");
        mainPnl2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total amount in words :");
        mainPnl2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, -1, -1));

        totalAmntInWordLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        totalAmntInWordLbl.setForeground(new java.awt.Color(255, 255, 0));
        mainPnl2.add(totalAmntInWordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 648, 450, -1));

        courseSlbl.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        courseSlbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPnl2.add(courseSlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 180, -1));

        getContentPane().add(mainPnl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 950, 665));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
         clearTable();
        searchFees();
       
    }//GEN-LAST:event_submitBtnActionPerformed
    public void clearTable(){
        DefaultTableModel model1 = (DefaultTableModel)tableFees.getModel();
        model1.setRowCount(0);
    }
    
    DefaultTableModel model;
    private void searchFees(){
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
       
        String fromDate= dateFormat.format(staartDate.getDate());
        String toDate = dateFormat.format(endDate.getDate());
        String course1 = courseCombo.getSelectedItem().toString();
        
     String query = "SELECT * FROM fees WHERE date BETWEEN '"+fromDate+"' AND '"+toDate+"' AND course='"+course1+"'";
     fmsConnection fc = new fmsConnection(query);
     try{
      ResultSet rs = fc.pStmt.executeQuery();
      double totalAmount=0.0;
      while(rs.next()){
//roll_no | first_name | last_name | father_name|mother_name|DOB|courseID|contact_no|email| address| country
          String rollNo     = rs.getString("roll_no");
          String recieptNO  = rs.getString("reciept_no");
          String studentName   = rs.getString("recieved_from");
          String courseName      = rs.getString("course");
          String amount      = rs.getString("amount");
          String remark     = rs.getString("remark");
          String date1     = rs.getDate("date").toString();
          
//        String recieptNo = rs.getString("");
          Object obj[] = {recieptNO,rollNo,studentName,courseName,amount,remark,date1};
          model=(DefaultTableModel)tableFees.getModel();
          model.addRow(obj);
          
          totalAmount = totalAmount+Double.parseDouble(amount);
     }
      courseSlbl.setText(course1);
      amountLbl.setText(String.valueOf(totalAmount));
      //converting netAmount into integer and then pass value to convert
       String word= NumberToWordsConverter.convert((int)totalAmount);
       totalAmntInWordLbl.setText(word+" only.");
    }
    catch(Exception e){
        e.printStackTrace();
    }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

     private void darkTheme(){
//     printBtn.setBackground(new Color(128,128,128));
     MainPnl1.setBackground(new Color(128,128,128));
     mainPnl2.setBackground(new Color(64,64,64));
     repoLogoLbl.setForeground(new Color(255,255,255));
     homeBtn.setBackground(new Color(64,64,64)); 
     searchBtn.setBackground(new Color(64,64,64)); 
     EditBtn.setBackground(new Color(64,64,64)); 
     CourseBtn.setBackground(new Color(64,64,64));
     viewAllRecBtn.setBackground(new Color(64,64,64));
     backBtn.setBackground(new Color(64,64,64)); 
     logoutBtn.setBackground(new Color(64,64,64)); 
    
    }
    private void lightTheme(){
//     printBtn.setBackground(new Color(0,204,51));
     MainPnl1.setBackground(new Color(242,135,5));
     mainPnl2.setBackground(new Color(242,159,100));
    repoLogoLbl.setForeground(new Color(242,203,5));
      homeBtn.setBackground(new Color(242,203,5)); 
    searchBtn.setBackground(new Color(242,203,5)); 
      EditBtn.setBackground(new Color(242,203,5)); 
    CourseBtn.setBackground(new Color(242,203,5));
viewAllRecBtn.setBackground(new Color(242,203,5));
      backBtn.setBackground(new Color(242,203,5)); 
    logoutBtn.setBackground(new Color(242,203,5)); 
    
    }
    
    //theme setCurrentTheme........................................................begin 2
    private void setCurrentTheme(String currentTheme){
        if(currentTheme.equalsIgnoreCase("dark")){
            selectDark();//here(in DB) true means dark theme
        }
        else{
            selectLight();//here(in DB) true means light theme
        }
    }
    //theme setCurrentTheme........................................................end
    
    // theme select.................................................................begin 3
    private void selectDark(){
        System.out.println("SelectDark");
        themeToggleButton.setText("Dark");
        themeToggleButton.setBackground(new Color(0, 0, 0));
        themeToggleButton.setForeground(new Color(255, 255, 255));
        darkTheme();
   
    }
    private void selectLight(){
         System.out.println("selectLight");
        themeToggleButton.setText("Light");
        themeToggleButton.setBackground(new Color(255, 255, 255));
        themeToggleButton.setForeground(new Color(0, 0, 0));
        lightTheme();
      
    }
    // theme select.................................................................end  3
    
    private void themeToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_themeToggleButtonItemStateChanged
        int state = evt.getStateChange();

        // if selectDark print dark theme in console
        if (state == java.awt.event.ItemEvent.SELECTED) {
            selectDark();
            Theme.setTheme("dark");
        }
        else { // else  print light theme theme in console
            selectLight();
            Theme.setTheme("light");
        }
    }//GEN-LAST:event_themeToggleButtonItemStateChanged

    private void themeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeToggleButtonActionPerformed

    }//GEN-LAST:event_themeToggleButtonActionPerformed

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.dispose();
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            homeBtn.setBackground(new Color(96, 96, 96));
        } else {
            homeBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            homeBtn.setBackground(new Color(64, 64, 64));
        } else {
            homeBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_homeBtnMouseExited

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        this.dispose();
        SearchRecord ad = new SearchRecord();
        ad.setVisible(true);
    }//GEN-LAST:event_searchBtnMouseClicked

    private void searchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            searchBtn.setBackground(new Color(96, 96, 96));
        } else {
            searchBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_searchBtnMouseEntered

    private void searchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            searchBtn.setBackground(new Color(64, 64, 64));
        } else {
            searchBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_searchBtnMouseExited

    private void EditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseClicked
        this.dispose();
        EditCourse ad = new EditCourse();
        ad.setVisible(true);
    }//GEN-LAST:event_EditBtnMouseClicked

    private void EditBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            EditBtn.setBackground(new Color(96, 96, 96));
        } else {
            EditBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_EditBtnMouseEntered

    private void EditBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            EditBtn.setBackground(new Color(64, 64, 64));
        } else {
            EditBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_EditBtnMouseExited

    private void CourseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseClicked
        this.dispose();
        AdminViewCourse ad = new AdminViewCourse();
        ad.setVisible(true);
    }//GEN-LAST:event_CourseBtnMouseClicked

    private void CourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            CourseBtn.setBackground(new Color(96, 96, 96));
        } else {
            CourseBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_CourseBtnMouseEntered

    private void CourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            CourseBtn.setBackground(new Color(64, 64, 64));
        } else {
            CourseBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_CourseBtnMouseExited

    private void viewAllRecBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllRecBtnMouseClicked
        this.dispose();
        ViewAllRecords ad = new ViewAllRecords();
        ad.setVisible(true);
    }//GEN-LAST:event_viewAllRecBtnMouseClicked

    private void viewAllRecBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllRecBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            viewAllRecBtn.setBackground(new Color(96, 96, 96));
        } else {
            viewAllRecBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_viewAllRecBtnMouseEntered

    private void viewAllRecBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllRecBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            viewAllRecBtn.setBackground(new Color(64, 64, 64));
        } else {
            viewAllRecBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_viewAllRecBtnMouseExited

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        this.dispose();
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
    }//GEN-LAST:event_backBtnMouseClicked

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            backBtn.setBackground(new Color(96, 96, 96));
        } else {
            backBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            backBtn.setBackground(new Color(64, 64, 64));
        } else {
            backBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_backBtnMouseExited

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        this.dispose();
        HomeMain ad = new HomeMain();
        ad.setVisible(true);
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            logoutBtn.setBackground(new Color(96, 96, 96));
        } else {
            logoutBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            logoutBtn.setBackground(new Color(64, 64, 64));
        } else {
            logoutBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_logoutBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CourseBtn;
    private javax.swing.JPanel EditBtn;
    private javax.swing.JPanel MainPnl1;
    private javax.swing.JLabel amountLbl;
    private javax.swing.JPanel backBtn;
    private javax.swing.JComboBox<String> courseCombo;
    private javax.swing.JLabel courseSlbl;
    private javax.swing.JLabel crselbl;
    private com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JPanel homeBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JPanel mainPnl2;
    private javax.swing.JLabel repoLogoLbl;
    private javax.swing.JPanel searchBtn;
    private com.toedter.calendar.JDateChooser staartDate;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTable tableFees;
    private javax.swing.JToggleButton themeToggleButton;
    private javax.swing.JLabel totalAmntInWordLbl;
    private javax.swing.JPanel viewAllRecBtn;
    // End of variables declaration//GEN-END:variables
}
