/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ravi_jaiswal
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public SignUp() {
          this.setResizable(false);
     addTitleIcon();
        initComponents();
    }
    private void addTitleIcon(){
        ImageIcon icon = new ImageIcon("src/Images/college.png");
        this.setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fNameTxt = new javax.swing.JTextField();
        lNameTxt = new javax.swing.JTextField();
        uNameTxt = new javax.swing.JTextField();
        passTxt = new javax.swing.JPasswordField();
        confPassTxt = new javax.swing.JPasswordField();
        dobTxt = new com.toedter.calendar.JDateChooser();
        contTxt = new javax.swing.JTextField();
        repoLogoLbl7 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jSeparator1 = new javax.swing.JSeparator();
        fNameErrMsg = new javax.swing.JLabel();
        lNameErrMsg = new javax.swing.JLabel();
        uNameErrMsg = new javax.swing.JLabel();
        passErrMsg = new javax.swing.JLabel();
        confPassErrMsg = new javax.swing.JLabel();
        dobErrMsg = new javax.swing.JLabel();
        cntctErrMsg = new javax.swing.JLabel();
        repoLogoLbl15 = new javax.swing.JLabel();
        repoLogoLbl6 = new javax.swing.JLabel();
        repoLogoLbl8 = new javax.swing.JLabel();
        repoLogoLbl1 = new javax.swing.JLabel();
        repoLogoLbl2 = new javax.swing.JLabel();
        repoLogoLbl10 = new javax.swing.JLabel();
        repoLogoLbl9 = new javax.swing.JLabel();
        repoLogoLbl11 = new javax.swing.JLabel();
        repoLogoLbl12 = new javax.swing.JLabel();
        repoLogoLbl13 = new javax.swing.JLabel();
        repoLogoLbl16 = new javax.swing.JLabel();
        repoLogoLbl17 = new javax.swing.JLabel();
        repoLogoLbl18 = new javax.swing.JLabel();
        repoLogoLbl19 = new javax.swing.JLabel();
        repoLogoLbl20 = new javax.swing.JLabel();
        repoLogoLbl21 = new javax.swing.JLabel();
        repoLogoLbl22 = new javax.swing.JLabel();
        repoLogoLbl23 = new javax.swing.JLabel();
        repoLogoLbl24 = new javax.swing.JLabel();
        repoLogoLbl25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signup");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(121, 25, 255));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(235, 0, 19));
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ux.png"))); // NOI18N
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 280, 280));

        jLabel1.setFont(new java.awt.Font("Jokerman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SignUp");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 130, 120, 60));

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 710, 120, 40));

        jButton3.setBackground(new java.awt.Color(93, 153, 216));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        jButton3.setText("Login?");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 710, 120, 40));

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 197, 2));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 197, 2));
        kGradientPanel2.setOpaque(false);
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name :");
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 70, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name :");
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 120, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username :");
        kGradientPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 170, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password :");
        kGradientPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 210, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm Password :");
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 260, 200, 30));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("D.O.B :");
        kGradientPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 300, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 23)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact No. :");
        kGradientPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 350, 140, 30));

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signup.png"))); // NOI18N
        jButton1.setText("SIGNUP");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 150, 40));

        fNameTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        fNameTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTxtActionPerformed(evt);
            }
        });
        fNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fNameTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fNameTxtKeyTyped(evt);
            }
        });
        kGradientPanel2.add(fNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 70, 170, 30));

        lNameTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTxtActionPerformed(evt);
            }
        });
        lNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lNameTxtKeyReleased(evt);
            }
        });
        kGradientPanel2.add(lNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 115, 170, 30));

        uNameTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        uNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNameTxtActionPerformed(evt);
            }
        });
        uNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uNameTxtKeyReleased(evt);
            }
        });
        kGradientPanel2.add(uNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 165, 170, 30));

        passTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        passTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passTxtKeyReleased(evt);
            }
        });
        kGradientPanel2.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 210, 170, 30));

        confPassTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        confPassTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confPassTxtActionPerformed(evt);
            }
        });
        confPassTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confPassTxtKeyReleased(evt);
            }
        });
        kGradientPanel2.add(confPassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 255, 170, 30));

        dobTxt.setPreferredSize(new java.awt.Dimension(88, 20));
        kGradientPanel2.add(dobTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 300, 170, 30));

        contTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        contTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contTxtActionPerformed(evt);
            }
        });
        contTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contTxtKeyReleased(evt);
            }
        });
        kGradientPanel2.add(contTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 350, 170, 30));

        repoLogoLbl7.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl7.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/analysis (1).png"))); // NOI18N
        kGradientPanel2.add(repoLogoLbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -260, 250, 300));

        kGradientPanel3.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel3.setkStartColor(new java.awt.Color(255, 255, 255));

        kGradientPanel4.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel4.setkStartColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        kGradientPanel2.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 96, 135, -1));
        kGradientPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        fNameErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fNameErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(fNameErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 100, 250, 20));

        lNameErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lNameErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(lNameErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 140, 250, 20));

        uNameErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        uNameErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(uNameErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 190, 250, 20));

        passErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(passErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 240, 240, 20));

        confPassErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        confPassErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(confPassErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 280, 240, 20));

        dobErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dobErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(dobErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 330, 240, 20));

        cntctErrMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cntctErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        kGradientPanel2.add(cntctErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 380, 210, 20));

        repoLogoLbl15.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl15.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/analysis (1).png"))); // NOI18N
        kGradientPanel2.add(repoLogoLbl15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 250, -1));

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 400, 490));

        repoLogoLbl6.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl6.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 250, 350));

        repoLogoLbl8.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl8.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 190, 250, 350));

        repoLogoLbl1.setFont(new java.awt.Font("Jokerman", 0, 30)); // NOI18N
        repoLogoLbl1.setForeground(new java.awt.Color(51, 199, 202));
        repoLogoLbl1.setText("Feature s of F.M.S...");
        kGradientPanel1.add(repoLogoLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 290, 40));

        repoLogoLbl2.setFont(new java.awt.Font("Jokerman", 0, 30)); // NOI18N
        repoLogoLbl2.setForeground(new java.awt.Color(255, 255, 51));
        repoLogoLbl2.setText("SignUp To get Access...");
        kGradientPanel1.add(repoLogoLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 340, 40));

        repoLogoLbl10.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl10.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -50, 250, 350));

        repoLogoLbl9.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl9.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, -180, 250, 350));

        repoLogoLbl11.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl11.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, -180, 250, 350));

        repoLogoLbl12.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl12.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, -180, 250, 350));

        repoLogoLbl13.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl13.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1)_1.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, -180, 250, 350));

        repoLogoLbl16.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl16.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 150, 120));

        repoLogoLbl17.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl17.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 100, 70));

        repoLogoLbl18.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl18.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 630, 70, 60));

        repoLogoLbl19.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl19.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 340, 100, 60));

        repoLogoLbl20.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl20.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 250, 80, 60));

        repoLogoLbl21.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl21.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 110, 150, 120));

        repoLogoLbl22.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl22.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 150, 120));

        repoLogoLbl23.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl23.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 100, 60));

        repoLogoLbl24.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl24.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireworks.png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 630, 70, 60));

        repoLogoLbl25.setFont(new java.awt.Font("Jokerman", 0, 20)); // NOI18N
        repoLogoLbl25.setForeground(new java.awt.Color(255, 255, 255));
        repoLogoLbl25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/artificial-intelligence (1).png"))); // NOI18N
        kGradientPanel1.add(repoLogoLbl25, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 440, 250, 350));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameTxtActionPerformed

    private void uNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uNameTxtActionPerformed

    private void lNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(myValidate()){//Submit button actions .............
        insertDataIntoDb(); 
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    //My methods..............................................
    String fName,lName,uName,pwd,cPwd,cntct;
    Date dob1;
    private boolean flag[]=new boolean[7];
   
    public boolean myValidate(){
         flag[0]=true;
         fName=fNameTxt.getText();
         lName=lNameTxt.getText();
         uName=uNameTxt.getText();
         pwd=passTxt.getText();
         cPwd=confPassTxt.getText();
         dob1=dobTxt.getDate();
         cntct=contTxt.getText();
        
         
         return checkEmptyField()&& passMatch(pwd,cPwd)&&flagResult(); 
    }
    private boolean flagResult(){
        boolean res=true;
        for (boolean b : flag) {
           res=res&&b; 
        }
        return res;
    }
    public boolean checkEmptyField(){//check for empty fields..........
    if(fName.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Firstname!");
        return false;
        }
        if(lName.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Lastname!");
        return false;
        }
        if(uName.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Username!");
        return false;
        }
        if(pwd.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Password!");
        return false;
        }
        if(cPwd.equals("")){
            JOptionPane.showMessageDialog(this, "please Confirm your password!");
        return false;
        }
        if(dob1==null){
            JOptionPane.showMessageDialog(this, "please Select your DOB!");
            System.out.println("date..................."+dob1);
        return false;
        }
        if(cntct.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter your Contact!");
        return false;
        }
     return true;
    }
    
    public boolean passMatch(String pass1, String pass2){
         if(!pass1.equals(pass2)){ 
             JOptionPane.showMessageDialog(this, "password and confirmPassword doesn't matched");
             return false;}
         return true;
    }
    
    public void reset(){
        fNameTxt.setText("");
        lNameTxt.setText("");
        uNameTxt.setText("");
        passTxt.setText("");
        confPassTxt.setText("");
        dobTxt.setDate(null);
        contTxt.setText("");
    }
    
    public boolean patternMatcher(String regex,String name){
    Pattern p = Pattern.compile(regex); 
    Matcher m= p.matcher(name);
    return m.find();
    }
    
    private void insertDataIntoDb(){
        //to convert default date format into yyyy-MM-dd format
         //note month must be MM not mm
        SimpleDateFormat dateFormat1= new SimpleDateFormat("yyyy-MM-dd");
        String dob2=dateFormat1.format(dob1);
        
        String query ="insert into signup(firstName,lastName,userName,password,contact,dob)values(?,?,?,?,?,?)";
        fmsConnection fc = new fmsConnection(query);
          
            
        try{
            fc.pStmt.setString(1,fName);
            fc.pStmt.setString(2,lName);
            fc.pStmt.setString(3,uName);
            fc.pStmt.setString(4,pwd);
            fc.pStmt.setLong(5,Long.parseLong(cntct));
            fc.pStmt.setString(6, dob2);

            fc.pStmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Signup Successfull...");
            fc.con.close();
        }
        catch(Exception e){
            System.out.println("Signup failed.");
            e.printStackTrace();
        }
    }
    
    
    
    //ends here...........................
    
    
    private void confPassTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confPassTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confPassTxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        AdminLogin login = new AdminLogin();
        login.setVisible(true);
        System.out.println("Login button clicked.");
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fNameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameTxtKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fNameTxtKeyTyped

    private void fNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameTxtKeyReleased
//         TODO add your handling code here:
        if(patternMatcher("^[a-zA-Z]+$",fNameTxt.getText())){
            fNameErrMsg.setText("");
            flag[1]=true;
        }
        else{
            fNameErrMsg.setText("*FName must contain only Alphabets[a-zA-Z]");
            flag[1]=false;
        }
    }//GEN-LAST:event_fNameTxtKeyReleased

    private void lNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNameTxtKeyReleased
        // TODO add your handling code here:
        if(patternMatcher("^[a-zA-Z]+$",lNameTxt.getText())){
            lNameErrMsg.setText("");
             flag[2]=true;
        }
        else{
            lNameErrMsg.setText("*LName must contain only Alphabets[a-zA-Z]");
            flag[2]=false;
        }
    }//GEN-LAST:event_lNameTxtKeyReleased

    private void uNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uNameTxtKeyReleased
        // TODO add your handling code here:
        if(patternMatcher("^[a-zA-Z]+$",uNameTxt.getText())){
            uNameErrMsg.setText("");
             flag[3]=true;
        }
        else{
            uNameErrMsg.setText("*UName must contain only Alphabets[a-zA-Z]");
             flag[3]=false;
        }
    }//GEN-LAST:event_uNameTxtKeyReleased

    private void passTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTxtKeyReleased
        // TODO add your handling code here:
        if(patternMatcher("^.{6,}",passTxt.getText())){
            passErrMsg.setText("");
             flag[4]=true;
        }
        else{
            passErrMsg.setText("*password minum of length(6)");
             flag[4]=false;
        }
    }//GEN-LAST:event_passTxtKeyReleased

    private void confPassTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confPassTxtKeyReleased
        // TODO add your handling code here:
        if(patternMatcher("^.{6,}",confPassTxt.getText())){
            confPassErrMsg.setText("");
             flag[5]=true;
        }
        else{
            confPassErrMsg.setText("*password minum of length(6)");
             flag[5]=false;
        }
    }//GEN-LAST:event_confPassTxtKeyReleased

    private void contTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contTxtKeyReleased
        // TODO add your handling code here:
        if(patternMatcher("^[6-8][0-9]{9}$",contTxt.getText())){
            cntctErrMsg.setText("");
             flag[6]=true;
        }
        else{
            cntctErrMsg.setText("*Invalid number");
             flag[6]=false;
        }
    }//GEN-LAST:event_contTxtKeyReleased

    private void contTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {//..........main function here..........
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cntctErrMsg;
    private javax.swing.JLabel confPassErrMsg;
    private javax.swing.JPasswordField confPassTxt;
    private javax.swing.JTextField contTxt;
    private javax.swing.JLabel dobErrMsg;
    private com.toedter.calendar.JDateChooser dobTxt;
    private javax.swing.JLabel fNameErrMsg;
    private javax.swing.JTextField fNameTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private javax.swing.JLabel lNameErrMsg;
    private javax.swing.JTextField lNameTxt;
    private javax.swing.JLabel passErrMsg;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JLabel repoLogoLbl1;
    private javax.swing.JLabel repoLogoLbl10;
    private javax.swing.JLabel repoLogoLbl11;
    private javax.swing.JLabel repoLogoLbl12;
    private javax.swing.JLabel repoLogoLbl13;
    private javax.swing.JLabel repoLogoLbl15;
    private javax.swing.JLabel repoLogoLbl16;
    private javax.swing.JLabel repoLogoLbl17;
    private javax.swing.JLabel repoLogoLbl18;
    private javax.swing.JLabel repoLogoLbl19;
    private javax.swing.JLabel repoLogoLbl2;
    private javax.swing.JLabel repoLogoLbl20;
    private javax.swing.JLabel repoLogoLbl21;
    private javax.swing.JLabel repoLogoLbl22;
    private javax.swing.JLabel repoLogoLbl23;
    private javax.swing.JLabel repoLogoLbl24;
    private javax.swing.JLabel repoLogoLbl25;
    private javax.swing.JLabel repoLogoLbl6;
    private javax.swing.JLabel repoLogoLbl7;
    private javax.swing.JLabel repoLogoLbl8;
    private javax.swing.JLabel repoLogoLbl9;
    private javax.swing.JLabel uNameErrMsg;
    private javax.swing.JTextField uNameTxt;
    // End of variables declaration//GEN-END:variables
}
