/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.Date;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Ravi_jaiswal
 */
public class SReciept1 extends javax.swing.JFrame {

    /**
     * Creates new form Fees
     */
    public SReciept1() {
        addTitleIcon();
          this.setResizable(false);
        initComponents();
        injectLastInfoFromDb();
        
    }
    private void addTitleIcon(){
        ImageIcon icon = new ImageIcon("src/Images/college.png");
        this.setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPnl2 = new javax.swing.JPanel();
        date_err_lbl = new javax.swing.JLabel();
        bankName_err_lbl = new javax.swing.JLabel();
        reciept_err_lbl = new javax.swing.JLabel();
        reciept_pnl = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        courselbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rollLbn = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        netAmountLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        endYearLbl = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        recieverSignLbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ddLbl1 = new javax.swing.JLabel();
        bankNameLbl1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        recieptLbl = new javax.swing.JLabel();
        modeOfPaymentLbl = new javax.swing.JLabel();
        ddLbl2 = new javax.swing.JLabel();
        bankNameLbl2 = new javax.swing.JLabel();
        recFromLbl = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        sgstLbl = new javax.swing.JLabel();
        gstLbl = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        ttlInWordsLbl = new javax.swing.JLabel();
        remarkLbl = new javax.swing.JLabel();
        amountLbl = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        startYearLbl = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        checkLbl1 = new javax.swing.JLabel();
        checkLbl2 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        MainPnl1 = new javax.swing.JPanel();
        themeToggleButton = new javax.swing.JToggleButton();
        printBtn = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        CourseBtn = new javax.swing.JPanel();
        crselbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SReciept");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPnl2.setBackground(new java.awt.Color(242, 159, 100));
        MainPnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date_err_lbl.setForeground(new java.awt.Color(255, 0, 51));
        MainPnl2.add(date_err_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 110, -1));

        bankName_err_lbl.setForeground(new java.awt.Color(255, 0, 51));
        MainPnl2.add(bankName_err_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 200, -1));

        reciept_err_lbl.setForeground(new java.awt.Color(255, 0, 0));
        MainPnl2.add(reciept_err_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 160, -1));

        reciept_pnl.setBackground(new java.awt.Color(255, 255, 255));
        reciept_pnl.setForeground(new java.awt.Color(102, 102, 102));
        reciept_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(0, 204, 204));
        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Mode of Payment");
        reciept_pnl.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, -1));

        jLabel7.setBackground(new java.awt.Color(0, 204, 204));
        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Reciept no: FMT");
        reciept_pnl.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, -1));

        dateLbl.setBackground(new java.awt.Color(0, 204, 204));
        dateLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(102, 51, 255));
        dateLbl.setText("Date :");
        reciept_pnl.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 39, 110, 40));

        jLabel21.setBackground(new java.awt.Color(0, 204, 204));
        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("GSTIN :     SJDKH4DJK");
        reciept_pnl.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 80, 190, -1));

        jLabel10.setBackground(new java.awt.Color(0, 204, 204));
        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Recieved from");
        reciept_pnl.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, -1));

        jLabel19.setBackground(new java.awt.Color(0, 204, 204));
        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("The following payment in the college office for the year :");
        reciept_pnl.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 380, -1));

        courselbl.setBackground(new java.awt.Color(0, 204, 204));
        courselbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        courselbl.setForeground(new java.awt.Color(102, 51, 255));
        courselbl.setText("Course :");
        reciept_pnl.add(courselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 80, -1));

        jLabel8.setBackground(new java.awt.Color(0, 204, 204));
        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("to");
        reciept_pnl.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 20, -1));

        rollLbn.setBackground(new java.awt.Color(0, 204, 204));
        rollLbn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        rollLbn.setForeground(new java.awt.Color(102, 51, 255));
        rollLbn.setText("Roll No:");
        reciept_pnl.add(rollLbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 120, -1));

        jLabel24.setBackground(new java.awt.Color(0, 204, 204));
        jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel24.setText("Sr.No. :");
        reciept_pnl.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 295, 60, 20));
        reciept_pnl.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 720, 10));

        jLabel25.setBackground(new java.awt.Color(0, 204, 204));
        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 51, 255));
        jLabel25.setText("1");
        reciept_pnl.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 40, -1));

        netAmountLbl.setBackground(new java.awt.Color(0, 204, 204));
        netAmountLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        netAmountLbl.setForeground(new java.awt.Color(102, 51, 255));
        netAmountLbl.setText("Net Amount(Rs) :");
        reciept_pnl.add(netAmountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 160, 30));
        reciept_pnl.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 720, 10));

        jLabel27.setBackground(new java.awt.Color(0, 204, 204));
        jLabel27.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel27.setText("GST(9 %):");
        reciept_pnl.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 80, -1));

        jLabel28.setBackground(new java.awt.Color(0, 204, 204));
        jLabel28.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel28.setText("SGST(9 %):");
        reciept_pnl.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 80, -1));
        reciept_pnl.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 210, 10));

        jLabel22.setBackground(new java.awt.Color(0, 204, 204));
        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel22.setText("Total in Words:");
        reciept_pnl.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 120, -1));

        endYearLbl.setBackground(new java.awt.Color(0, 204, 204));
        endYearLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        endYearLbl.setForeground(new java.awt.Color(102, 51, 255));
        endYearLbl.setText("end");
        reciept_pnl.add(endYearLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 40, -1));
        reciept_pnl.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 210, 10));

        recieverSignLbl.setBackground(new java.awt.Color(0, 204, 204));
        recieverSignLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        recieverSignLbl.setForeground(new java.awt.Color(102, 51, 255));
        recieverSignLbl.setText("Reciever Sign :");
        reciept_pnl.add(recieverSignLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 120, -1));

        jLabel15.setBackground(new java.awt.Color(0, 204, 204));
        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Reciept no: FMT");
        reciept_pnl.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, -1));

        jLabel23.setBackground(new java.awt.Color(0, 204, 204));
        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Mode of Payment");
        reciept_pnl.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, -1));

        ddLbl1.setBackground(new java.awt.Color(0, 204, 204));
        ddLbl1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        ddLbl1.setForeground(new java.awt.Color(102, 102, 102));
        ddLbl1.setText("DD no. : ");
        reciept_pnl.add(ddLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, -1));

        bankNameLbl1.setBackground(new java.awt.Color(0, 204, 204));
        bankNameLbl1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        bankNameLbl1.setForeground(new java.awt.Color(102, 102, 102));
        bankNameLbl1.setText("Bank name:");
        reciept_pnl.add(bankNameLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, -1));

        jLabel31.setBackground(new java.awt.Color(0, 204, 204));
        jLabel31.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Recieved from");
        reciept_pnl.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, -1));

        recieptLbl.setBackground(new java.awt.Color(0, 204, 204));
        recieptLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        recieptLbl.setForeground(new java.awt.Color(102, 51, 255));
        recieptLbl.setText("Reciept no: FMT");
        reciept_pnl.add(recieptLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 110, -1));

        modeOfPaymentLbl.setBackground(new java.awt.Color(0, 204, 204));
        modeOfPaymentLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        modeOfPaymentLbl.setForeground(new java.awt.Color(102, 51, 255));
        modeOfPaymentLbl.setText("Mode of Payment");
        reciept_pnl.add(modeOfPaymentLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 140, -1));

        ddLbl2.setBackground(new java.awt.Color(0, 204, 204));
        ddLbl2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        ddLbl2.setForeground(new java.awt.Color(102, 51, 255));
        ddLbl2.setText("DD no. : ");
        reciept_pnl.add(ddLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 110, -1));

        bankNameLbl2.setBackground(new java.awt.Color(0, 204, 204));
        bankNameLbl2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        bankNameLbl2.setForeground(new java.awt.Color(102, 51, 255));
        bankNameLbl2.setText("Bank name:");
        reciept_pnl.add(bankNameLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 440, -1));

        recFromLbl.setBackground(new java.awt.Color(0, 204, 204));
        recFromLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        recFromLbl.setForeground(new java.awt.Color(102, 51, 255));
        recFromLbl.setText("Recieved from");
        reciept_pnl.add(recFromLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 380, -1));

        jLabel35.setBackground(new java.awt.Color(0, 204, 204));
        jLabel35.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Date :");
        reciept_pnl.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 50, 50, -1));

        jLabel36.setBackground(new java.awt.Color(0, 204, 204));
        jLabel36.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Roll No:");
        reciept_pnl.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 60, -1));

        jLabel38.setBackground(new java.awt.Color(0, 204, 204));
        jLabel38.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel38.setText("Amount(Rs) :");
        reciept_pnl.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 295, 110, -1));

        sgstLbl.setBackground(new java.awt.Color(0, 204, 204));
        sgstLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        sgstLbl.setForeground(new java.awt.Color(102, 51, 255));
        sgstLbl.setText("SGST(9 %):");
        reciept_pnl.add(sgstLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 80, -1));

        gstLbl.setBackground(new java.awt.Color(0, 204, 204));
        gstLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        gstLbl.setForeground(new java.awt.Color(102, 51, 255));
        gstLbl.setText("GST(9 %):");
        reciept_pnl.add(gstLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 110, -1));

        jLabel41.setBackground(new java.awt.Color(0, 204, 204));
        jLabel41.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel41.setText("Reciever Sign :");
        reciept_pnl.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 120, -1));

        ttlInWordsLbl.setBackground(new java.awt.Color(0, 204, 204));
        ttlInWordsLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        ttlInWordsLbl.setForeground(new java.awt.Color(102, 51, 255));
        ttlInWordsLbl.setText("Total in Words:");
        reciept_pnl.add(ttlInWordsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 480, 400, -1));

        remarkLbl.setBackground(new java.awt.Color(0, 204, 204));
        remarkLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        remarkLbl.setForeground(new java.awt.Color(102, 51, 255));
        remarkLbl.setText("Remark :");
        reciept_pnl.add(remarkLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 510, 370, 20));

        amountLbl.setBackground(new java.awt.Color(0, 204, 204));
        amountLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        amountLbl.setForeground(new java.awt.Color(102, 51, 255));
        amountLbl.setText("Amount(Rs) :");
        reciept_pnl.add(amountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 110, -1));

        jLabel45.setBackground(new java.awt.Color(0, 204, 204));
        jLabel45.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel45.setText("Remark :");
        reciept_pnl.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 120, -1));

        startYearLbl.setBackground(new java.awt.Color(0, 204, 204));
        startYearLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        startYearLbl.setForeground(new java.awt.Color(102, 51, 255));
        startYearLbl.setText("Start");
        reciept_pnl.add(startYearLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 50, -1));

        jLabel47.setBackground(new java.awt.Color(0, 204, 204));
        jLabel47.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 102, 102));
        jLabel47.setText("Course :");
        reciept_pnl.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, -1));

        jLabel48.setBackground(new java.awt.Color(0, 204, 204));
        jLabel48.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel48.setText("Heads :");
        reciept_pnl.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 295, 60, -1));

        checkLbl1.setBackground(new java.awt.Color(0, 204, 204));
        checkLbl1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        checkLbl1.setForeground(new java.awt.Color(102, 102, 102));
        checkLbl1.setText("Check no. : ");
        reciept_pnl.add(checkLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, -1));

        checkLbl2.setBackground(new java.awt.Color(0, 204, 204));
        checkLbl2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        checkLbl2.setForeground(new java.awt.Color(102, 51, 255));
        checkLbl2.setText("Check no. : ");
        reciept_pnl.add(checkLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 110, -1));

        jLabel29.setBackground(new java.awt.Color(0, 204, 204));
        jLabel29.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 51, 255));
        jLabel29.setText("1");
        reciept_pnl.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 40, -1));

        MainPnl2.add(reciept_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 770, 630));

        getContentPane().add(MainPnl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 810, 665));

        MainPnl1.setBackground(new java.awt.Color(242, 135, 5));
        MainPnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        themeToggleButton.setBackground(new java.awt.Color(255, 255, 255));
        themeToggleButton.setText("Light");
        themeToggleButton.setFocusable(false);
        themeToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                themeToggleButtonItemStateChanged(evt);
            }
        });
        themeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeToggleButtonActionPerformed(evt);
            }
        });
        MainPnl1.add(themeToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 60, -1));

        printBtn.setBackground(new java.awt.Color(242, 203, 5));
        printBtn.setForeground(new java.awt.Color(255, 255, 255));
        printBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printBtnMouseExited(evt);
            }
        });
        printBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Print");
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel49MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel49MouseExited(evt);
            }
        });
        printBtn.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 70, -1));

        MainPnl1.add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 205, 50));

        CourseBtn.setBackground(new java.awt.Color(242, 203, 5));
        CourseBtn.setForeground(new java.awt.Color(255, 255, 255));
        CourseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CourseBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CourseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CourseBtnMouseExited(evt);
            }
        });
        CourseBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crselbl.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        crselbl.setForeground(new java.awt.Color(255, 255, 255));
        crselbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/course_btn.png"))); // NOI18N
        crselbl.setText("Courses");
        CourseBtn.add(crselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        MainPnl1.add(CourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 205, 50));

        backBtn.setBackground(new java.awt.Color(242, 203, 5));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn.png"))); // NOI18N
        jLabel17.setText("Back");
        backBtn.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        MainPnl1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 205, 50));

        logoutBtn.setBackground(new java.awt.Color(242, 203, 5));
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        logoutBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout_btn.png"))); // NOI18N
        jLabel11.setText("Logout");
        logoutBtn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        MainPnl1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 205, 50));

        homeBtn.setBackground(new java.awt.Color(242, 203, 5));
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_btn.png"))); // NOI18N
        jLabel12.setText("Home");
        homeBtn.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        MainPnl1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 205, 50));

        getContentPane().add(MainPnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 665));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//....................................................................................................
    
    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {                                     
        
    }      //My methods......................................................................................
    String recieptNo,bankName,dd_no,check_no,recieved_from,amount,roll_no;
    Date date;
    
        private void InjectsLastInfoFromDb() {//fetchiching courses from table and add data into course combo......
        String query="SELECT * FROM course";
        fmsConnection con = new fmsConnection(query);
        
        try {
            ResultSet rs= con.pStmt.executeQuery();
            while(rs.next()){
//               courseCombo.addItem(rs.getString("courseName"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(SReciept1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void newRecieptNo(){
    String query = "SELECT MAX(reciept_no) from fees";    
    fmsConnection con1 = new fmsConnection(query);
        try {
            ResultSet rs = con1.pStmt.executeQuery();
            System.out.println(rs);
                 if(rs.next()) {                    
                    int max =rs.getInt(1);
//                    recieptTxt.setText(String.valueOf(max+1)); 
                }
            con1.con.close();
        } catch (SQLException ex) {
            Logger.getLogger(SReciept1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void injectLastInfoFromDb(){
        
        String query ="SELECT * from fees WHERE reciept_no=(SELECT MAX(reciept_no) from fees)";
        fmsConnection fc = new fmsConnection(query);
       try{
            ResultSet rs= fc.pStmt.executeQuery();
            rs.next();
            recieptLbl.setText(rs.getString("reciept_no"));
            dateLbl.setText(rs.getString("date"));
            //...............................................................start
            modeOfPaymentLbl.setText(rs.getString("payment_mode"));
            if(rs.getString("payment_mode").equalsIgnoreCase("cash")){
            ddLbl1.setVisible(false);
            ddLbl2.setVisible(false);
            checkLbl1.setVisible(false);
            checkLbl2.setVisible(false);
            bankNameLbl1.setVisible(false);
            bankNameLbl2.setVisible(false);
            }
            if(rs.getString("payment_mode").equalsIgnoreCase("dd")){
            ddLbl1.setVisible(true);
            ddLbl2.setVisible(true);
            checkLbl1.setVisible(false);
            checkLbl2.setVisible(false);
            bankNameLbl1.setVisible(true);
            bankNameLbl2.setVisible(true);
            }
            if(rs.getString("payment_mode").equalsIgnoreCase("check")){
            ddLbl1.setVisible(false);
            ddLbl2.setVisible(false);
            checkLbl1.setVisible(true);
            checkLbl2.setVisible(true);
            bankNameLbl1.setVisible(true);
            bankNameLbl2.setVisible(true);
            }
            if(rs.getString("payment_mode").equalsIgnoreCase("card")){
            ddLbl1.setVisible(false);
            ddLbl2.setVisible(false);
            checkLbl1.setVisible(false);
            checkLbl2.setVisible(false);
            bankNameLbl1.setVisible(true);
            bankNameLbl2.setVisible(true);
            }
            //...............................................................end
            ddLbl2.setText(rs.getString("dd_no"));
            checkLbl2.setText(rs.getString("check_no"));
            bankNameLbl2.setText(rs.getString("bank_name"));
            recFromLbl.setText(rs.getString("recieved_from"));
            
           startYearLbl.setText(rs.getString("start_year"));
           endYearLbl.setText(rs.getString("end_year"));
           amountLbl.setText(rs.getString("amount"));
           sgstLbl.setText(rs.getString("sgst"));
           gstLbl.setText(rs.getString("gst"));
           ttlInWordsLbl.setText(rs.getString("Ttl_in_words"));
            rollLbn.setText(rs.getString("roll_no"));
            netAmountLbl.setText(rs.getString("total_amount"));
            remarkLbl.setText(rs.getString("remark"));
            courselbl.setText(rs.getString("course"));
            
            fc.con.close();
        }
        catch(Exception e){
            System.out.println("Signup failed.");
            e.printStackTrace();
        }
    }
    // themes--------------------------------------------------------------------begin
    private void darkTheme(){
     
     MainPnl1.setBackground(new Color(128,128,128));
     MainPnl2.setBackground(new Color(64,64,64));
     homeBtn.setBackground(new Color(64,64,64)); 
//     searchBtn.setBackground(new Color(64,64,64)); 
//     EditBtn.setBackground(new Color(64,64,64)); 
     CourseBtn.setBackground(new Color(64,64,64));
//     viewAllRecBtn.setBackground(new Color(64,64,64));
     backBtn.setBackground(new Color(64,64,64)); 
     logoutBtn.setBackground(new Color(64,64,64)); 
    printBtn.setBackground(new Color(64,64,64));
//    editBtn.setBackground(new Color(64,64,64));
    }
    private void lightTheme(){
          MainPnl1.setBackground(new Color(242,135,5));
     MainPnl2.setBackground(new Color(242,159,100));
      homeBtn.setBackground(new Color(242,203,5)); 
//    searchBtn.setBackground(new Color(242,203,5)); 
//      EditBtn.setBackground(new Color(242,203,5)); 
    CourseBtn.setBackground(new Color(242,203,5));
//viewAllRecBtn.setBackground(new Color(242,203,5));
      backBtn.setBackground(new Color(242,203,5)); 
    logoutBtn.setBackground(new Color(242,203,5)); 
     printBtn.setBackground(new Color(242,203,5));
//     editBtn.setBackground(new Color(242,203,5));

    
    } // themes--------------------------------------------------------------------end
    
    // preintreiept--------------------------------------------------------------------begin
    private void printReciept() {
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        job.setPrintable(new Printable() {
            @Override
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                pf.setOrientation(PageFormat.LANDSCAPE);
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47, 0.47);

                reciept_pnl.print(g2);
                return Printable.PAGE_EXISTS;

            }
        });
        
        boolean ok = job.printDialog();
        if (ok) {
            try {

                job.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }

        }
    }
    // preintreiept--------------------------------------------------------------------end
    //ends here...........................
    
    private void themeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeToggleButtonActionPerformed
    
    }//GEN-LAST:event_themeToggleButtonActionPerformed

    private void themeToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_themeToggleButtonItemStateChanged
         int state = evt.getStateChange();
 
                // if selected print dark theme in console
                if (state == java.awt.event.ItemEvent.SELECTED) {
                    System.out.println("Selected");
                    themeToggleButton.setText("Dark");
                    themeToggleButton.setBackground(new Color(0,0,0));
                    themeToggleButton.setForeground(new Color(255,255,255));
                    darkTheme();
                }
                else { // else  print light theme theme in console

                    System.out.println("Deselected");
                     themeToggleButton.setText("Light");
                     themeToggleButton.setBackground(new Color(255,255,255));
                     themeToggleButton.setForeground(new Color(0,0,0));
                     lightTheme();
                }
    }//GEN-LAST:event_themeToggleButtonItemStateChanged

    private void jLabel49MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel49MouseEntered

    private void jLabel49MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel49MouseExited

    private void printBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printBtnMouseClicked
        printReciept();
    }//GEN-LAST:event_printBtnMouseClicked

    private void printBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_printBtnMouseEntered

    private void printBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_printBtnMouseExited

    private void CourseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseClicked
        this.dispose();
        StudentViewCourse ad = new StudentViewCourse();
        ad.setVisible(true);
    }//GEN-LAST:event_CourseBtnMouseClicked

    private void CourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            CourseBtn.setBackground(new Color(96, 96, 96));
        } else {
            CourseBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_CourseBtnMouseEntered

    private void CourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            CourseBtn.setBackground(new Color(64, 64, 64));
        } else {
            CourseBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_CourseBtnMouseExited

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        this.dispose();
        StudentDashboard ad = new StudentDashboard();
        ad.setVisible(true);
    }//GEN-LAST:event_backBtnMouseClicked

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            backBtn.setBackground(new Color(96, 96, 96));
        } else {
            backBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            backBtn.setBackground(new Color(64, 64, 64));
        } else {
            backBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_backBtnMouseExited

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
       this.dispose();
        StudentDashboard ad = new StudentDashboard();
        ad.setVisible(true);
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            logoutBtn.setBackground(new Color(96, 96, 96));
        } else {
            logoutBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            logoutBtn.setBackground(new Color(64, 64, 64));
        } else {
            logoutBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_logoutBtnMouseExited

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.dispose();
        StudentDashboard ad = new StudentDashboard();
        ad.setVisible(true);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            homeBtn.setBackground(new Color(96, 96, 96));
        } else {
            homeBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            homeBtn.setBackground(new Color(64, 64, 64));
        } else {
            homeBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_homeBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SReciept1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SReciept1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SReciept1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SReciept1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SReciept1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CourseBtn;
    private javax.swing.JPanel MainPnl1;
    private javax.swing.JPanel MainPnl2;
    private javax.swing.JLabel amountLbl;
    private javax.swing.JPanel backBtn;
    private javax.swing.JLabel bankNameLbl1;
    private javax.swing.JLabel bankNameLbl2;
    private javax.swing.JLabel bankName_err_lbl;
    private javax.swing.JLabel checkLbl1;
    private javax.swing.JLabel checkLbl2;
    private javax.swing.JLabel courselbl;
    private javax.swing.JLabel crselbl;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel date_err_lbl;
    private javax.swing.JLabel ddLbl1;
    private javax.swing.JLabel ddLbl2;
    private javax.swing.JLabel endYearLbl;
    private javax.swing.JLabel gstLbl;
    private javax.swing.JPanel homeBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JLabel modeOfPaymentLbl;
    private javax.swing.JLabel netAmountLbl;
    private javax.swing.JPanel printBtn;
    private javax.swing.JLabel recFromLbl;
    private javax.swing.JLabel recieptLbl;
    private javax.swing.JLabel reciept_err_lbl;
    private javax.swing.JPanel reciept_pnl;
    private javax.swing.JLabel recieverSignLbl;
    private javax.swing.JLabel remarkLbl;
    private javax.swing.JLabel rollLbn;
    private javax.swing.JLabel sgstLbl;
    private javax.swing.JLabel startYearLbl;
    private javax.swing.JToggleButton themeToggleButton;
    private javax.swing.JLabel ttlInWordsLbl;
    // End of variables declaration//GEN-END:variables

    

    
}
