/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Ravi_jaiswal
 */
public class UpdateLatestFees extends javax.swing.JFrame {

    /**
     * Creates new form Fees
     */
    String currentTheme;
    public UpdateLatestFees() {
        addTitleIcon();
          this.setResizable(false);
        initComponents();
        selectedCashMethodByDefault();
        injectCourseIntoList();
        insertLatestDataIntoForm();
        //make changes from here...................................
         flag[2]=true;
         flag[3]=true;
         //make changes to here.....................................
         
        //theme settings..................................................begin 1
        currentTheme=Theme.getTheme();
        setCurrentTheme(currentTheme);
        //theme settings..................................................end
         
    }
    private void addTitleIcon(){
        ImageIcon icon = new ImageIcon("src/Images/college.png");
        this.setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPnl2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        recieptTxt = new javax.swing.JTextField();
        paymentOptionCombo = new javax.swing.JComboBox<>();
        Date1 = new com.toedter.calendar.JDateChooser();
        ddTxt = new javax.swing.JTextField();
        ddLbl = new javax.swing.JLabel();
        bankNameLbl = new javax.swing.JLabel();
        checkTxt = new javax.swing.JTextField();
        checkLbl = new javax.swing.JLabel();
        date_err_lbl = new javax.swing.JLabel();
        bankName_err_lbl = new javax.swing.JLabel();
        reciept_err_lbl = new javax.swing.JLabel();
        bankNameTxt = new javax.swing.JTextField();
        MainPnl1 = new javax.swing.JPanel();
        themeToggleButton = new javax.swing.JToggleButton();
        homeBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        searehBtn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        EditBtn = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        CourseBtn = new javax.swing.JPanel();
        crselbl = new javax.swing.JLabel();
        viewAllRecBtn = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        backBtn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        mainPnl3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        recievedFromTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        startYearTxt = new com.toedter.calendar.JYearChooser();
        endYearTxt = new com.toedter.calendar.JYearChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        courseCombo = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        courseTxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarkTxt = new javax.swing.JTextArea();
        totalInWordsTxt = new javax.swing.JTextField();
        totalAmountTxt = new javax.swing.JTextField();
        sGstTxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        amountTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        printBtn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        amount_err_lbl2 = new javax.swing.JLabel();
        gstTxt = new javax.swing.JTextField();
        rollNoTxt = new javax.swing.JTextField();
        rollno_err_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UpdateLatestFees");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPnl2.setBackground(new java.awt.Color(242, 159, 100));
        MainPnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 204, 204));
        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Reciept no: FMT");
        MainPnl2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, -1));

        jLabel9.setBackground(new java.awt.Color(0, 204, 204));
        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("Mode of Payment");
        MainPnl2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, -1));

        jLabel20.setBackground(new java.awt.Color(0, 204, 204));
        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 255, 255));
        jLabel20.setText("Date :");
        MainPnl2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 50, 50, -1));

        jLabel21.setBackground(new java.awt.Color(0, 204, 204));
        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 255, 255));
        jLabel21.setText("GSTIN :     SJDKH4DJK");
        MainPnl2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 80, 190, -1));

        recieptTxt.setEditable(false);
        recieptTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                recieptTxtKeyReleased(evt);
            }
        });
        MainPnl2.add(recieptTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 60, 160, 25));

        paymentOptionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DD", "Check", "Cash", "Card" }));
        paymentOptionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentOptionComboActionPerformed(evt);
            }
        });
        MainPnl2.add(paymentOptionCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 90, -1, 25));

        Date1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Date1KeyReleased(evt);
            }
        });
        MainPnl2.add(Date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 50, 135, 25));
        MainPnl2.add(ddTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 160, 25));

        ddLbl.setBackground(new java.awt.Color(0, 204, 204));
        ddLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        ddLbl.setForeground(new java.awt.Color(204, 255, 255));
        ddLbl.setText("DD no. : ");
        MainPnl2.add(ddLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, -1));

        bankNameLbl.setBackground(new java.awt.Color(0, 204, 204));
        bankNameLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        bankNameLbl.setForeground(new java.awt.Color(204, 255, 255));
        bankNameLbl.setText("Bank name:");
        MainPnl2.add(bankNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, -1));
        MainPnl2.add(checkTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 160, 25));

        checkLbl.setBackground(new java.awt.Color(0, 204, 204));
        checkLbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        checkLbl.setForeground(new java.awt.Color(204, 255, 255));
        checkLbl.setText("Check no. :");
        MainPnl2.add(checkLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, -1));

        date_err_lbl.setForeground(new java.awt.Color(255, 0, 51));
        MainPnl2.add(date_err_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 110, -1));

        bankName_err_lbl.setForeground(new java.awt.Color(255, 0, 51));
        MainPnl2.add(bankName_err_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 200, -1));

        reciept_err_lbl.setForeground(new java.awt.Color(255, 0, 0));
        MainPnl2.add(reciept_err_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 160, -1));

        bankNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bankNameTxtKeyReleased(evt);
            }
        });
        MainPnl2.add(bankNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 160, 25));

        getContentPane().add(MainPnl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 860, 180));

        MainPnl1.setBackground(new java.awt.Color(242, 135, 5));
        MainPnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        themeToggleButton.setBackground(new java.awt.Color(255, 255, 255));
        themeToggleButton.setText("Light");
        themeToggleButton.setFocusable(false);
        themeToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                themeToggleButtonItemStateChanged(evt);
            }
        });
        themeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeToggleButtonActionPerformed(evt);
            }
        });
        MainPnl1.add(themeToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 60, -1));

        homeBtn.setBackground(new java.awt.Color(242, 203, 5));
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_btn.png"))); // NOI18N
        jLabel12.setText("Home");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        homeBtn.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        MainPnl1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 205, 50));

        searehBtn.setBackground(new java.awt.Color(242, 203, 5));
        searehBtn.setForeground(new java.awt.Color(255, 255, 255));
        searehBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searehBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searehBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searehBtnMouseExited(evt);
            }
        });
        searehBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_btn.png"))); // NOI18N
        jLabel13.setText("S Record");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        searehBtn.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, -1));

        MainPnl1.add(searehBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 205, 50));

        EditBtn.setBackground(new java.awt.Color(242, 203, 5));
        EditBtn.setForeground(new java.awt.Color(255, 255, 255));
        EditBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditBtnMouseExited(evt);
            }
        });
        EditBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit_btn.png"))); // NOI18N
        jLabel14.setText("Edit Course");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        EditBtn.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        MainPnl1.add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 205, 50));

        CourseBtn.setBackground(new java.awt.Color(242, 203, 5));
        CourseBtn.setForeground(new java.awt.Color(255, 255, 255));
        CourseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CourseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CourseBtnMouseExited(evt);
            }
        });
        CourseBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crselbl.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        crselbl.setForeground(new java.awt.Color(255, 255, 255));
        crselbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/course_btn.png"))); // NOI18N
        crselbl.setText("Course ");
        crselbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crselblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crselblMouseExited(evt);
            }
        });
        CourseBtn.add(crselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, 30));

        MainPnl1.add(CourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 205, 50));

        viewAllRecBtn.setBackground(new java.awt.Color(242, 203, 5));
        viewAllRecBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewAllRecBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewAllRecBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewAllRecBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewAllRecBtnMouseExited(evt);
            }
        });
        viewAllRecBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/records_btn.png"))); // NOI18N
        jLabel16.setText(" Records");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        viewAllRecBtn.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 30));

        MainPnl1.add(viewAllRecBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 205, 50));

        backBtn.setBackground(new java.awt.Color(242, 203, 5));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn.png"))); // NOI18N
        jLabel17.setText("Back");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });
        backBtn.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        MainPnl1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 205, 50));

        logoutBtn.setBackground(new java.awt.Color(242, 203, 5));
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        logoutBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Jokerman", 1, 21)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout_btn.png"))); // NOI18N
        jLabel11.setText("Logout");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        logoutBtn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, -1));

        MainPnl1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 205, 50));

        getContentPane().add(MainPnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 665));

        mainPnl3.setBackground(new java.awt.Color(242, 159, 100));
        mainPnl3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 204, 204));
        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("Recieved from");
        mainPnl3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, -1));
        mainPnl3.add(recievedFromTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 280, 25));

        jLabel6.setBackground(new java.awt.Color(0, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Roll No:");
        mainPnl3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 10, 60, -1));

        jLabel19.setBackground(new java.awt.Color(0, 204, 204));
        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 255, 255));
        jLabel19.setText("The following payment in the college office for the year :");
        mainPnl3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 380, -1));

        startYearTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startYearTxtMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                startYearTxtMouseReleased(evt);
            }
        });
        mainPnl3.add(startYearTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));
        mainPnl3.add(endYearTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 204, 204));
        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("to");
        mainPnl3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 40, -1));

        jLabel18.setBackground(new java.awt.Color(0, 204, 204));
        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 255, 255));
        jLabel18.setText("Course :");
        mainPnl3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        courseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboActionPerformed(evt);
            }
        });
        mainPnl3.add(courseCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 160, 25));

        jLabel24.setBackground(new java.awt.Color(0, 204, 204));
        jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 255, 255));
        jLabel24.setText("Sr.No. :");
        mainPnl3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, 20));
        mainPnl3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 720, 10));
        mainPnl3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 720, 10));

        jLabel25.setBackground(new java.awt.Color(0, 204, 204));
        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 255, 255));
        jLabel25.setText("Heads :");
        mainPnl3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 60, -1));

        jLabel26.setBackground(new java.awt.Color(0, 204, 204));
        jLabel26.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 255, 255));
        jLabel26.setText("Amount(Rs) :");
        mainPnl3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 110, -1));
        mainPnl3.add(courseTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 311, 28));

        jLabel27.setBackground(new java.awt.Color(0, 204, 204));
        jLabel27.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 255, 255));
        jLabel27.setText("GST(9 %):");
        mainPnl3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 80, -1));

        jLabel28.setBackground(new java.awt.Color(0, 204, 204));
        jLabel28.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 255, 255));
        jLabel28.setText("SGST(9 %):");
        mainPnl3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 80, -1));

        jLabel22.setBackground(new java.awt.Color(0, 204, 204));
        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 255, 255));
        jLabel22.setText("Total in Words:");
        mainPnl3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, -1));

        jLabel29.setBackground(new java.awt.Color(0, 204, 204));
        jLabel29.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 255, 255));
        jLabel29.setText("Remark :");
        mainPnl3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 120, -1));

        remarkTxt.setColumns(20);
        remarkTxt.setRows(5);
        jScrollPane1.setViewportView(remarkTxt);

        mainPnl3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 333, 310, 100));
        mainPnl3.add(totalInWordsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 311, 28));
        mainPnl3.add(totalAmountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 150, 25));
        mainPnl3.add(sGstTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 150, 25));
        mainPnl3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 210, 10));

        amountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTxtActionPerformed(evt);
            }
        });
        amountTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountTxtKeyReleased(evt);
            }
        });
        mainPnl3.add(amountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 150, 25));
        mainPnl3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 210, 10));

        jLabel30.setBackground(new java.awt.Color(0, 204, 204));
        jLabel30.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 255, 255));
        jLabel30.setText("Reciever Sign :");
        mainPnl3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 120, -1));

        printBtn.setBackground(new java.awt.Color(255, 102, 0));
        printBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printBtn.setForeground(new java.awt.Color(255, 255, 255));
        printBtn.setText("Update");
        printBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        mainPnl3.add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 110, 30));

        jLabel23.setBackground(new java.awt.Color(0, 204, 204));
        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 255, 255));
        jLabel23.setText("Recieved from");
        mainPnl3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, -1));

        amount_err_lbl2.setForeground(new java.awt.Color(255, 0, 51));
        mainPnl3.add(amount_err_lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 140, 0));
        mainPnl3.add(gstTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 150, 25));

        rollNoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rollNoTxtKeyReleased(evt);
            }
        });
        mainPnl3.add(rollNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 10, 150, 25));

        rollno_err_lbl.setForeground(new java.awt.Color(255, 0, 0));
        mainPnl3.add(rollno_err_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 190, -1));

        getContentPane().add(mainPnl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 860, 485));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//....................................................................................................
    private void selectedCashMethodByDefault(){
    paymentOptionCombo.setSelectedIndex(2);
    }
    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {                                     
        
    }  
    private void paymentOptionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentOptionComboActionPerformed
      if(paymentOptionCombo.getSelectedIndex()==0){//dd
          checkLbl.setVisible(false);
          checkTxt.setVisible(false);
          ddLbl.setVisible(true);
          ddTxt.setVisible(true);
          bankNameLbl.setVisible(true);
          bankNameTxt.setVisible(true);
          
          //if change from one payment method to another text field should be clean from previous entered data
          ddTxt.setText("");
          bankNameTxt.setText("");
      }
      if(paymentOptionCombo.getSelectedIndex()==1){//check
          ddLbl.setVisible(false);
          ddTxt.setVisible(false);
          checkLbl.setVisible(true);
          checkTxt.setVisible(true);
          bankNameLbl.setVisible(true);
          bankNameTxt.setVisible(true);
          
          //if change from one payment method to another text field should be clean from previous entered data
          checkTxt.setText("");
          bankNameTxt.setText("");
      }
      if(paymentOptionCombo.getSelectedItem().toString().equals("Cash")){//Cash
          ddLbl.setVisible(false);
          ddTxt.setVisible(false);
          checkLbl.setVisible(false);
          checkTxt.setVisible(false);
          bankNameLbl.setVisible(false);
          bankNameTxt.setVisible(false);
          
          //if change from one payment method to another text field should be clean from previous entered data
          
          bankNameTxt.setText("");
      }
      if(paymentOptionCombo.getSelectedIndex()==3){//Card
          ddLbl.setVisible(false);
          ddTxt.setVisible(false);
          checkLbl.setVisible(false);
          checkTxt.setVisible(false);
          bankNameLbl.setVisible(true);
          bankNameTxt.setVisible(true);
      }
    }//GEN-LAST:event_paymentOptionComboActionPerformed
    //My methods......................................................................................
    String recieptNo,bankName,dd_no,check_no,recieved_from,amount,roll_no;
    Date date;
    private boolean flag[]=new boolean[4];
   
    public boolean myValidate(){//my validate function...........................
         flag[0]=true;
         flag[1]=true;
         
         recieptNo=recieptTxt.getText();
         date=Date1.getDate();
         check_no=checkTxt.getText();
         dd_no=ddTxt.getText();
         bankName=bankNameTxt.getText();
         recieved_from=recievedFromTxt.getText();
         roll_no=rollNoTxt.getText();
         amount=amountTxt.getText();
         
         return checkEmptyField()&&flagResult(); 
    }
    
    private boolean flagResult(){
        boolean res=true;
        for (boolean b : flag) {
           res=res&&b; 
           System.out.println(b);
           System.out.println(res+":res---------");
        }
        System.out.println("final result"+res);
        return res;
    }
    
    public boolean checkEmptyField(){//check for empty fields..............................
        if(recieptNo.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Reciept no.!");
        return false;
        }
        if(date==null){
            JOptionPane.showMessageDialog(this, "please Select Date!");
            System.out.println("date..................."+date);
        return false;
        }
        if(paymentOptionCombo.getSelectedItem().equals("Check")){
            if( check_no.equals("")){
                JOptionPane.showMessageDialog(this, "please Enter check no.!");
                 return false;
            }
            if( bankName.equals("")){
                JOptionPane.showMessageDialog(this, "please Enter Bank Name!");
                 return false;
            }
        }
        if(paymentOptionCombo.getSelectedItem().equals("DD")){
            if( dd_no.equals("")){
                JOptionPane.showMessageDialog(this, "please Enter DD no.!");
                 return false;
            }
            if( bankName.equals("")){
                JOptionPane.showMessageDialog(this, "please Enter Bank Name!");
                 return false;
            }
        }
        if(paymentOptionCombo.getSelectedItem().equals("Card")){
            
            if( bankName.equals("")){
                JOptionPane.showMessageDialog(this, "please Enter Bank Name!");
                 return false;
            }
        }
        if(recieved_from.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Recieved from.!");
        return false;
        }
        
        if(roll_no.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Roll no.!");
        return false;
        }
        
        if(amount.equals("")){
            JOptionPane.showMessageDialog(this, "please Enter Amount!");
        return false;
        }
        
     return true;
    }
    
   
    
//    public void reset(){
//        fNameTxt.setText("");
//        lNameTxt.setText("");
//        uNameTxt.setText("");
//        passTxt.setText("");
//        confPassTxt.setText("");
//        dobTxt.setDate(null);
//        contTxt.setText("");
//    }
    
    public boolean patternMatcher1(String regex,String name){
    Pattern p = Pattern.compile(regex); 
    Matcher m= p.matcher(name);
    return m.find();
    }
    
    private void injectCourseIntoList() {//fetchiching courses from table and add data into course combo......
        String query="SELECT * FROM course";
        fmsConnection con = new fmsConnection(query);
        
        try {
            ResultSet rs= con.pStmt.executeQuery();
            while(rs.next()){
               courseCombo.addItem(rs.getString("courseName"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateLatestFees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
//    private void newRecieptNo(){
//    String query = "SELECT MAX(reciept_no) from fees";    
//    fmsConnection con1 = new fmsConnection(query);
//        try {
//            ResultSet rs = con1.pStmt.executeQuery();
//            System.out.println(rs);
//                 if(rs.next()) {                    
//                    int max =rs.getInt(1);
//                    recieptTxt.setText(String.valueOf(max+1)); 
//                }
//            con1.con.close();
//        } catch (SQLException ex) {
//            Logger.getLogger(UpdateLatestFees.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//    }
    
    private boolean updateLatestDataIntoDb(){
        //to convert default date format into yyyy-MM-dd format
         //note month must be MM not mm
        
        SimpleDateFormat dateFormat1= new SimpleDateFormat("yyyy-MM-dd");
        
        String date2=dateFormat1.format(Date1.getDate());

        

        // 1
        String query ="UPDATE fees "
                + "SET reciept_no=?,check_no=?,bank_name=?,date=?,recieved_from=?,roll_no=?,course=?,total_amount=?,remark=?,payment_mode=?,dd_no=?,start_year=?,end_year=?,amount=?,sgst=?,gst=?,Ttl_in_words=?"
                + "WHERE reciept_no='"+Integer.parseInt(recieptTxt.getText())+"'"; //(SELECT MAX(reciept_no))"; don't use this
        fmsConnection fc = new fmsConnection(query);
          
            
        try{
            
            fc.pStmt.setString(1,recieptTxt.getText());
            fc.pStmt.setString(2,checkTxt.getText());
            fc.pStmt.setString(3,bankNameTxt.getText());
          
            fc.pStmt.setString(4,date2);
           
            fc.pStmt.setString(5,recievedFromTxt.getText());
            fc.pStmt.setInt(6, Integer.parseInt(rollNoTxt.getText()));
          
            fc.pStmt.setString(7, courseTxt.getText());
            fc.pStmt.setInt(8, (int)Float.parseFloat(totalAmountTxt.getText()));
            fc.pStmt.setString(9, remarkTxt.getText());
            fc.pStmt.setString(10, paymentOptionCombo.getSelectedItem().toString());
            fc.pStmt.setString(11,ddTxt.getText() );
            
            fc.pStmt.setInt(12,startYearTxt.getYear() );
            fc.pStmt.setInt(13,endYearTxt.getYear() );
            fc.pStmt.setInt(14,Integer.parseInt(amountTxt.getText()));
            fc.pStmt.setString(15,sGstTxt.getText() );
            fc.pStmt.setString(16,gstTxt.getText() );
            fc.pStmt.setString(17,totalInWordsTxt.getText());
            
           

            fc.pStmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Update Successfull...");
            fc.con.close();
            return true;
        }
        catch(Exception e){
            System.out.println("Update failed.");
            e.printStackTrace();
             return false;
        }
        
    }
    
    private void insertLatestDataIntoForm(){
         String query ="SELECT * FROM fees WHERE reciept_no=(SELECT MAX(reciept_no) FROM fees)";
        fmsConnection fc = new fmsConnection(query);
      
        try{
        ResultSet rs = fc.pStmt.executeQuery();
        rs.next();//to move pointer towards table first row
        recieptTxt.setText(String.valueOf(rs.getInt("reciept_no")));
      
        

            //...............................................................start
//                        .setText(rs.getString("date"));
            
            paymentOptionCombo.setSelectedItem(rs.getString("payment_mode"));
            
            checkTxt.setText(rs.getString("check_no"));
            ddTxt.setText(rs.getString("dd_no"));
            bankNameTxt.setText(rs.getString("bank_name"));
            recievedFromTxt.setText(rs.getString("recieved_from"));

            startYearTxt.setYear(rs.getInt("start_year"));
            endYearTxt.setYear(rs.getInt("end_year"));
            amountTxt.setText(rs.getString("amount"));
            sGstTxt.setText(rs.getString("sgst"));
            gstTxt.setText(rs.getString("gst"));
            totalInWordsTxt.setText(rs.getString("Ttl_in_words"));
            rollNoTxt.setText(rs.getString("roll_no"));
            totalAmountTxt.setText(rs.getString("total_amount"));
            remarkTxt.setText(rs.getString("remark"));
            courseTxt.setText(rs.getString("course"));
            courseCombo.setSelectedItem(rs.getString("course"));
            //...............................................................end
            fc.con.close();
        }
        catch(Exception e){
            System.out.println("parsing data from DB failed.");
            e.printStackTrace();
             
        }
    }
    
    private void darkTheme(){
     printBtn.setBackground(new Color(128,128,128));
     MainPnl1.setBackground(new Color(128,128,128));
     MainPnl2.setBackground(new Color(64,64,64));
     mainPnl3.setBackground(new Color(64,64,64)); 
     homeBtn.setBackground(new Color(64,64,64)); 
     searehBtn.setBackground(new Color(64,64,64)); 
     EditBtn.setBackground(new Color(64,64,64)); 
     CourseBtn.setBackground(new Color(64,64,64));
     viewAllRecBtn.setBackground(new Color(64,64,64));
     backBtn.setBackground(new Color(64,64,64)); 
     logoutBtn.setBackground(new Color(64,64,64)); 
    
    }
    private void lightTheme(){
     printBtn.setBackground(new Color(0,204,51));
     MainPnl1.setBackground(new Color(0,204,204));
     MainPnl2.setBackground(new Color(242,203,5));
     mainPnl3.setBackground(new Color(242,203,5)); 
      homeBtn.setBackground(new Color(242,203,5)); 
    searehBtn.setBackground(new Color(242,203,5)); 
      EditBtn.setBackground(new Color(242,203,5)); 
    CourseBtn.setBackground(new Color(242,203,5));
viewAllRecBtn.setBackground(new Color(242,203,5));
      backBtn.setBackground(new Color(242,203,5)); 
    logoutBtn.setBackground(new Color(242,203,5)); 
    
    }
    //ends here...........................
    
    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        if(myValidate()){
            System.out.println("Validation done...");
            if(updateLatestDataIntoDb()){
                this.dispose();
                AReciept reciept= new AReciept();
                reciept.setVisible(true);
            }
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void Date1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Date1KeyReleased
     
    }//GEN-LAST:event_Date1KeyReleased

    private void recieptTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recieptTxtKeyReleased
//        if(patternMatcher1("^[1-9][0-9]*$",recieptTxt.getText())){
//            reciept_err_lbl.setText("");
//             flag[2]=true;
//        }
//        else{
//            reciept_err_lbl.setText("*invalid reciept no.)");
//             flag[2]=true;
//        }
    }//GEN-LAST:event_recieptTxtKeyReleased
            
    private void amountTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountTxtKeyReleased
       if(patternMatcher1("^[1-9][0-9]*$",amountTxt.getText())){
            amount_err_lbl2.setText("");
             flag[3]=true;
        }
        else{
            amount_err_lbl2.setText("no. only then press Enter");
             flag[3]=false;
        }
    }//GEN-LAST:event_amountTxtKeyReleased

    private void bankNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bankNameTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_bankNameTxtKeyReleased

    private void rollNoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollNoTxtKeyReleased
        if(patternMatcher1("^[1-9][0-9]*$",rollNoTxt.getText())){
            rollno_err_lbl.setText("");
             flag[2]=true;
        }
        else{
            rollno_err_lbl.setText("numbers only*");
             flag[2]=false;
        }
    }//GEN-LAST:event_rollNoTxtKeyReleased

    private void amountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTxtActionPerformed
       if(amount_err_lbl2.getText().equals("")){
        float tax;
       float netAmount;
       int amount1=Integer.parseInt(amountTxt.getText());
       tax=(0.09f)*amount1;
       gstTxt.setText(String.valueOf(tax));
       sGstTxt.setText(String.valueOf(tax));
       netAmount=amount1+tax+tax;
       totalAmountTxt.setText(String.valueOf(netAmount));
       
       //converting netAmount into integer and then pass value to convert
       String word= NumberToWordsConverter.convert((int)netAmount);
       totalInWordsTxt.setText(word+" only.");
       }
       else{
       gstTxt.setText("");
       sGstTxt.setText("");
       totalAmountTxt.setText("");
       }
    }//GEN-LAST:event_amountTxtActionPerformed

    private void courseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboActionPerformed
        String course;
        course =courseCombo.getSelectedItem().toString();
        courseTxt.setText(course);
    }//GEN-LAST:event_courseComboActionPerformed

    private void startYearTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startYearTxtMouseClicked
       
    }//GEN-LAST:event_startYearTxtMouseClicked

    private void startYearTxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startYearTxtMouseReleased
      
    }//GEN-LAST:event_startYearTxtMouseReleased

    //theme setCurrentTheme........................................................begin 2
    private void setCurrentTheme(String currentTheme){
        if(currentTheme.equalsIgnoreCase("dark")){
            selectDark();//here(in DB) true means dark theme
        }
        else{
            selectLight();//here(in DB) true means light theme
        }
    }
    //theme setCurrentTheme........................................................end
    
    // theme select.................................................................begin 3
    private void selectDark(){
        System.out.println("SelectDark");
        themeToggleButton.setText("Dark");
        themeToggleButton.setBackground(new Color(0, 0, 0));
        themeToggleButton.setForeground(new Color(255, 255, 255));
        darkTheme();
   
    }
    private void selectLight(){
         System.out.println("selectLight");
        themeToggleButton.setText("Light");
        themeToggleButton.setBackground(new Color(255, 255, 255));
        themeToggleButton.setForeground(new Color(0, 0, 0));
        lightTheme();
      
    }
    // theme select.................................................................end  3
    
    private void themeToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_themeToggleButtonItemStateChanged
        int state = evt.getStateChange();

        // if selectDark print dark theme in console
        if (state == java.awt.event.ItemEvent.SELECTED) {
            selectDark();
            Theme.setTheme("dark");
        }
        else { // else  print light theme theme in console
            selectLight();
            Theme.setTheme("light");
        }
    }//GEN-LAST:event_themeToggleButtonItemStateChanged

    private void themeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeToggleButtonActionPerformed

    }//GEN-LAST:event_themeToggleButtonActionPerformed

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered

    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited

    }//GEN-LAST:event_jLabel12MouseExited

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        this.dispose();
        AdminDashboard home = new AdminDashboard();
        home.setVisible(true);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            homeBtn.setBackground(new Color(96, 96, 96));
        } else {
            homeBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            homeBtn.setBackground(new Color(64, 64, 64));
        } else {
            homeBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_homeBtnMouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseExited

    private void searehBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searehBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            searehBtn.setBackground(new Color(96, 96, 96));
        } else {
            searehBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_searehBtnMouseEntered

    private void searehBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searehBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            searehBtn.setBackground(new Color(64, 64, 64));
        } else {
            searehBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_searehBtnMouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseExited

    private void EditBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            EditBtn.setBackground(new Color(96, 96, 96));
        } else {
            EditBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_EditBtnMouseEntered

    private void EditBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseExited

        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            EditBtn.setBackground(new Color(64, 64, 64));
        } else {
            EditBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_EditBtnMouseExited

    private void crselblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crselblMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_crselblMouseEntered

    private void crselblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crselblMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_crselblMouseExited

    private void CourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            CourseBtn.setBackground(new Color(96, 96, 96));
        } else {
            CourseBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_CourseBtnMouseEntered

    private void CourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            CourseBtn.setBackground(new Color(64, 64, 64));
        } else {
            CourseBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_CourseBtnMouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseExited

    private void viewAllRecBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllRecBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            viewAllRecBtn.setBackground(new Color(96, 96, 96));
        } else {
            viewAllRecBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_viewAllRecBtnMouseEntered

    private void viewAllRecBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllRecBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            viewAllRecBtn.setBackground(new Color(64, 64, 64));
        } else {
            viewAllRecBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_viewAllRecBtnMouseExited

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseExited

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        this.dispose();
        AdminDashboard home = new AdminDashboard();
        home.setVisible(true);
    }//GEN-LAST:event_backBtnMouseClicked

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            backBtn.setBackground(new Color(96, 96, 96));
        } else {
            backBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            backBtn.setBackground(new Color(64, 64, 64));
        } else {
            backBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_backBtnMouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseExited

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        this.dispose();
        AdminLogin login = new AdminLogin();
        login.setVisible(true);
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            logoutBtn.setBackground(new Color(96, 96, 96));
        } else {
            logoutBtn.setBackground(new Color(29,89,78));
        }
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        if (themeToggleButton.getText().equalsIgnoreCase("dark")) {
            logoutBtn.setBackground(new Color(64, 64, 64));
        } else {
            logoutBtn.setBackground(new Color(242,203,5));
        }
    }//GEN-LAST:event_logoutBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateLatestFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateLatestFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateLatestFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateLatestFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateLatestFees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CourseBtn;
    private com.toedter.calendar.JDateChooser Date1;
    private javax.swing.JPanel EditBtn;
    private javax.swing.JPanel MainPnl1;
    private javax.swing.JPanel MainPnl2;
    private javax.swing.JTextField amountTxt;
    private javax.swing.JLabel amount_err_lbl2;
    private javax.swing.JPanel backBtn;
    private javax.swing.JLabel bankNameLbl;
    private javax.swing.JTextField bankNameTxt;
    private javax.swing.JLabel bankName_err_lbl;
    private javax.swing.JLabel checkLbl;
    private javax.swing.JTextField checkTxt;
    private javax.swing.JComboBox<String> courseCombo;
    private javax.swing.JTextField courseTxt;
    private javax.swing.JLabel crselbl;
    private javax.swing.JLabel date_err_lbl;
    private javax.swing.JLabel ddLbl;
    private javax.swing.JTextField ddTxt;
    private com.toedter.calendar.JYearChooser endYearTxt;
    private javax.swing.JTextField gstTxt;
    private javax.swing.JPanel homeBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JPanel mainPnl3;
    private javax.swing.JComboBox<String> paymentOptionCombo;
    private javax.swing.JButton printBtn;
    private javax.swing.JTextField recieptTxt;
    private javax.swing.JLabel reciept_err_lbl;
    private javax.swing.JTextField recievedFromTxt;
    private javax.swing.JTextArea remarkTxt;
    private javax.swing.JTextField rollNoTxt;
    private javax.swing.JLabel rollno_err_lbl;
    private javax.swing.JTextField sGstTxt;
    private javax.swing.JPanel searehBtn;
    private com.toedter.calendar.JYearChooser startYearTxt;
    private javax.swing.JToggleButton themeToggleButton;
    private javax.swing.JTextField totalAmountTxt;
    private javax.swing.JTextField totalInWordsTxt;
    private javax.swing.JPanel viewAllRecBtn;
    // End of variables declaration//GEN-END:variables

    
}
